<!--
        	作者：vincedotnet@hotmail.com
        	时间：2015-05-28
        	描述：view的内部代码
        -->

<div class="mg-ttblk fixed">
    <span class="tt">创建新活动</span>
    <span class="glyphicon glyphicon-chevron-left mg-ttblk-i left" id="pge-cover-back"></span>
    <span class="glyphicon glyphicon-ok mg-ttblk-i right" id="pge-cover-save"></span>
</div>
<div class="big-box" style="margin-top:65px;">
    <div class="wp">
        <div class="glacker">
            <p class="inp-tt">活动主题 <span class="red">*</span></p>
            <input type="text" placeholder="活动的主题内容（限30个中文字）" maxlength="60" class="inp-txt full" />
        </div>
        <div class="glacker">
            <p class="inp-tt">活动时间</p>
            <ul class="row-duotab clearfix" style="margin-top:8px;">
                <li class="selected tab-bt" rel="add-c-tab-1">
                    <i class="glyphicon glyphicon-calendar"></i>
                    确定的日子
                </li>
                <li class="tab-bt" rel="add-c-tab-2">
                    <i class="glyphicon glyphicon-bullhorn"></i>
                    大家的意见
                </li>
            </ul>
            <div style="padding:10px 10px;border:1px solid #E2E2E2;border-top:none;">

                <div id="add-c-tab-1" class="selected tab-cont">
                    <p id="checked-time-solid"><span>请在下方选择活动时间</span></p>
                    <div class="mg-ttblk">
                        <span class="tt" id="jijj">十二月 2015</span>
                        <span class="glyphicon glyphicon-menu-left mg-ttblk-i left" id="to-last-month"></span>
                        <span class="glyphicon glyphicon-menu-right mg-ttblk-i right" id="to-next-month"></span>
                    </div>
                    <div id="calendar-check-time">
                        <div></div>
                    </div>
                </div>
                <div id="add-c-tab-2" class="tab-cont">
                    <p id="checked-time-range">
                        选择一个时间段，让小伙伴们各自选出方便的2个时间，从而根据大多数人的选择，得到最佳活动时间
                    </p>
                    <button class="rowbtn">开始</button>
                    <p id="px101">至</p>
                    <button class="rowbtn">结束</button>
                </div>
            </div>
        </div>

        <div class="glacker">
            <p class="inp-tt">地点</p>
            <input type="text" maxlength="60" class="inp-txt full" />
        </div>

        <div class="glacker">
            <p class="inp-tt">活动描述</p>
            <textarea class="inp-txt full"></textarea>
        </div>
    </div>
</div>

<!--
    作者：vincedotnet@hotmail.com
    时间：2015-06-01
    描述：footerbar 不在该页显示，所以要加入这个style隐藏footerbar
-->
<style>
    #footerbar {
        display:none !important;
    }
</style>