<div id="tv-frame">
    <div class="board">
        <div class="title">
            找回密码
        </div>
        <div class="content">
            <div class="row">
                <span class="font12px">请输入您的邮箱地址，我们将会通过邮件帮您找回密码</span>
            </div>
            <div class="row">
                <input type="text" placeholder="用户邮箱" id="email"/>
            </div>
            <div class="row">
                <button type="button" id="confirm-btn">发送邮件</button>
            </div>
        </div>
        <div class="bottom">
            <a href="<?php echo $this->url(array(), 'login') ?>">重新登录？</a>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#confirm-btn').click(function() {
            var email = $('#email').val();
            $.ajax({
                url: '<?php echo $this->url(array(), 'forgot-password') ?>',
                dataType: 'json',
                type: 'post',
                data: {email: email},
                success: function(response) {
                    if (response === 1) {
                        
                    } else {
                        
                    }
                }
            });
        });
    });
</script>