<!--
        	作者：vincedotnet@hotmail.com
        	时间：2015-05-28
        	描述：view的内部代码
        -->
<script src="<?php echo $this->jsPath("weixin/share.js"); ?>"></script>
<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/user.js"); ?>"></script>
<img id="share-headimg" style="position:absolute;top:-2000px;" src="<?php echo $this->headimgurl ?>">
<div class="big-box gamerbod nmt" style="display: none">
    <div class="wp relative">
        <img class="ssimg" src="" />
        <div class="rdcts">
            <div class="rdcrs">
                <span></span>
            </div>
            <div class="rdcfs">

            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="big-box">
    <div class="mg-ttblk" style="background:#333;color:#FFF;border-radius:5px 5px 0 0;">
        <span class="tt" id="jijj">十二月 2015</span>
        <span class="glyphicon glyphicon-menu-left mg-ttblk-i left" id="to-last-month"></span>
        <span class="glyphicon glyphicon-menu-right mg-ttblk-i right" id="to-next-month"></span>
    </div>
    <div id="real-calendar">
        <div>

        </div>
    </div>
</div>

<div class="big-box transparent">
    <button class="rowbtn" id="btn_share">
        <i class="glyphicon glyphicon-send"></i> 分享我的日历
    </button>
    <div class="clear-5"></div>
    <button class="rowbtn" id="pending" style="display: none">
        <i class="glyphicon glyphicon-pending" ></i> 查看未确定活动安排
    </button>
</div>
<script src="<?php echo $this->jsPath("action/index.js"); ?>"></script>
<script>
    var appid = '<?php echo $this->appid ?>';
//    var open_id = '<?php //echo $this->openid ?>//';
    var share_id = '<?php echo $this->share_id ?>';
    var nickname = '<?php echo $this->nickname ?>';
    var headimgurl = '<?php echo $this->headimgurl ?>';
    var is_share = false;
    var cur_meet_id = false;

</script>