<!--
        	作者：vincedotnet@hotmail.com
        	时间：2015-05-28
        	描述：view的内部代码
        -->
<script src="<?php echo $this->jsPath("weixin/share.js"); ?>"></script>
<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/user.js"); ?>"></script>
<div class="big-box gamerbod nmt" style="display: none">
    <div class="wp relative">
        <img class="ssimg" src="" />
        <div class="rdcts">
            <div class="rdcrs">
                <span></span>
            </div>
            <div class="rdcfs">

            </div>

        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="big-box">
    <div class="mg-ttblk" style="background:#333;color:#FFF;border-radius:5px 5px 0 0;">
        <span class="tt" id="jijj">十二月 2015</span>
        <span class="glyphicon glyphicon-menu-left mg-ttblk-i left" id="to-last-month"></span>
        <span class="glyphicon glyphicon-menu-right mg-ttblk-i right" id="to-next-month"></span>
    </div>
    <div id="real-calendar">
        <div>

        </div>
    </div>
</div>

<div class="big-box transparent">
    <button class="rowbtn" id="share">
        <i class="glyphicon glyphicon-send"></i> 分享我的日历
    </button>
    <div class="clear-5"></div>
    <button class="rowbtn" id="pending">
        <i class="glyphicon glyphicon-pending" ></i> 查看未确定活动安排
    </button>
</div>
<script src="<?php echo $this->jsPath("action/index.js"); ?>"></script>
<script>
    var appid = '<?php echo $this->appid ?>';
//    var open_id = '<?php //echo $this->openid ?>//';
    var share_id = '<?php echo $this->share_id ?>';
    var nickname = '<?php echo $this->nickname ?>';
    var headimgurl = '<?php echo $this->headimgurl ?>';
    var is_share = false;
    $(document).ready(function(){
        var now = new Date();
        $('#real-calendar div').Calendar({
            'weekStart' : 1,
            'date' : now
        }).on('changeDay', function(event) {
            var load_date = event.day.valueOf() + '-' + event.month.valueOf() + '-' + event.year.valueOf();

            $('#jijj').html(load_date);

            $('day_'+ event.day.valueOf()).addClass('selected');

//            if ($('#meet-list').attr('load_date') == load_date + "_load") {
//                $('#meet-list').html('');
//                $('#meet-list').attr('load_date', load_date);
//
//                return;
//            }

//            $('#meet-list').attr('load_date', load_date + "_load");

            var meetModel = new Meet();

            var user_id = localStorage.getItem('user_id');

            meetModel.Query(user_id, event.year.valueOf(), event.month.valueOf(),  event.day.valueOf());
        });

        if (share_id) {
            localStorage.setItem('share_id', share_id);
        }

        $('#jijj').html(now.getMonth() + 1 + "月-" + now.getFullYear() + "年");

        //测试
//        localStorage.clear();

//        if (open_id) {
//            localStorage.setItem('user_id', open_id);
//        }

        var user_id = localStorage.getItem('user_id');
//        alert(window.location.href);
        if (!user_id) {
            wx_Login(window.location.href);
        }
        else {
            var user_id = localStorage.getItem('user_id');
            var share_id = localStorage.getItem('share_id');
            //如果分享id不为空，则用分享id替换用户id
            if (share_id) {
                user_id = share_id;
            }

            getSchedule();
        }
    });
</script>