<!--
        	作者：vincedotnet@hotmail.com
        	时间：2015-05-28
        	描述：view的内部代码
        -->
<style>
    #top-bar {
        display: none;
    }
</style>
<script src="<?php echo $this->jsPath("weixin/share.js"); ?>"></script>
<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/user.js"); ?>"></script>
<img id="share-headimg" style="position:absolute;top:-2000px;" src="<?php echo $this->headimgurl ?>">
<div class="big-box gamerbod nmt" style="display: none">
    <div class="wp relative">
        <img class="ssimg" src="" />
        <div class="rdcts">
            <div class="rdcrs">
                <span></span>
            </div>
            <div class="rdcfs">

            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>

<div class="big-box">
    <div class="mg-ttblk" style="background:#333;color:#FFF;border-radius:5px 5px 0 0;">
        <span class="tt" id="jijj"></span>
        <span class="glyphicon glyphicon-menu-left mg-ttblk-i left" id="to-last-month"></span>
        <span class="glyphicon glyphicon-menu-right mg-ttblk-i right" id="to-next-month"></span>
    </div>
    <div id="real-calendar">
        <div>

        </div>
    </div>
</div>

<div class="big-box transparent">
    <button class="rowbtn" id="btn_share">
        <i class="glyphicon glyphicon-send"></i> 分享我的日历
    </button>
    <div class="clear-5"></div>
    <button class="rowbtn" id="pending" style="display: none">
        <i class="glyphicon glyphicon-pending" ></i> 查看未确定活动安排
    </button>
</div>

<div>
    <div class="act-detail-cover"></div>
    <div class="act-detail-bd">
        <div class="mg-ttblk absolute">
            <span class="tt" id="title">快来参加</span>
            <span class="glyphicon glyphicon-remove mg-ttblk-i right cls"></span>
        </div>
        <div class="wp">
            <div class="glacker gp">
                <p class="inp-tt">活动时间</p>
                <div class="p33i9plp label label-success">已确定时间</div>
                <div class="lbke" id="selected_date">2015年6月15日</div>
            </div>
            <div class="glacker gp">
                <p class="inp-tt">活动主题</p>
                <label class="lbke" id="meet_text">你的技能</label>
            </div>
            <div class="glacker gp">
                <p class="inp-tt">地点</p>
                <label class="lbke" id="address">暂无地址</label>
            </div>
            <div class="glacker gp">
                <p class="inp-tt">已同意参加的人</p>
                <ul class="busr-lst"></ul>
                <div class="clear"></div>
            </div>
            <div class="glacker p33comts gp">
                <p id="test-tt" class="inp-tt words-ttt">暂无留言</p>
                <div id="word-list"></div>
                <p class="inp-tt" style="margin-top:5px;">发表留言</p>
                <textarea id="word_text" class="inp-txt full"></textarea>
                <button class="rowbtn" id="word_submit">提交</button>
                <div class="clear-5"></div>
                <!--            <button class="rowbtn" style="display: none" id="letmejoin">我加入</button>-->
                <!--            <button class="rowbtn" style="display: none" id="letmeleave">我退出</button>-->
                <!--            <div class="clear-5"></div>style="display: none" style="display: none"-->
                <!--            <button class="rowbtn"  id="letmejoin">我加入</button>-->
                <button class="rowbtn red" style="display: none" id="btn_leave">我退出</button>
                <button class="rowbtn" style="display: none" id="btn_join">我加入</button>
                <div class="clear-5"></div>
                <button class="rowbtn red" style="margin-top: 50px;" id="close_meet">关闭活动</button>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->jsPath("action/index.js"); ?>"></script>
<script>
    var appid = '<?php echo $this->appid ?>';
//    var open_id = '<?php //echo $this->openid ?>//';
    var share_id = '<?php echo $this->share_id ?>';
    var nickname = '<?php echo $this->nickname ?>';
    var headimgurl = '<?php echo $this->headimgurl ?>';
    var is_share = false;
    var cur_meet_id = false;
</script>