<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/meet_pending.js"); ?>"></script>
<div class="mg-ttblk fixed">
    <!-- 此处最多显示8个汉字 -->
    <span class="tt" id="title"></span>
    <span class="glyphicon glyphicon-chevron-left mg-ttblk-i left" id="pge-cover-back"></span>
</div>
<div class="big-box" style="margin-top:65px;">
    <div class="mg-listc">
        <div id="meet-list">

        </div>
    </div>
</div>
<style>
    /*#footerbar {*/
        /*display:none !important;*/
    /*}*/
</style>
<script type="text/javascript">

</script>
