<style>

</style>
<form role="form" method="post">

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-title">注册新会员</h1>
            </div>
            <div class="col-md-12">
                <?php if ($this->error): ?>
                    <div class="alert alert-danger"><?php echo $this->error ?></div>
                <?php endif; ?>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label>邮箱</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="输入邮箱">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label>用户名</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="输入用户名">
                </div>
            </div>
<!--            <div class="col-md-12">
                <div class="form-group">
                    <label>真实姓名</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="输入真实姓名">
                </div>
            </div>-->
            <div class="col-md-12">
                <div class="form-group">
                    <label>密码</label>
                    <input type="password" class="form-control" maxlength="18" id="password" name="password" placeholder="输入密码">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">

                    <label>性别</label>
                    <div>
                        <input id="male" type="radio" name="gender" value="male" checked="checked" />
                        <label for="male">男</label>
                        &nbsp;
                        <input id="female" type="radio" name="gender" value="female" />
                        <label for="female">女</label>
                    </div>

                </div>
            </div>



            <div class="col-md-12">
                <div class="form-group">

                    <label>出生年份</label>
                    <div>
                        <select name="age">
                            <?php
                            $curYear = date('Y', time());
                            $age = $curYear - 99;

                            for ($i = 0; $i < 100; $i++) {
                                $tmp = $age + $i;

                                $select = "";

                                if ($tmp == 1985)
                                    $select = "selected";

                                echo "<option value ='" . $tmp . "' " . $select . ">" . $tmp . "</option>";
                            }
                            ?>
                        </select>
                    </div>

                </div>
            </div>


            <div class="col-md-12">
                <button type="submit" id="reg" class="btn btn-success">确认提交</button>
            </div>
        </div>


    </div>
</form>
<div class="P_tmp">
    <a class="btn btn-success btn-sm register-link rtbtn pull-right" href="<?php echo $this->url(array(), 'login') ?>">登录</a>
</div>
<script type="text/javascript">
    (function($) {
        $(document).ready(function() {
            var n = $('.register-link').clone(true);
            $('#m3g-header .col-md-12').append(n);
        });
    })(jQuery);
</script>