<style>
    #bigc2-img-wp {
        display:block;
    }
    #bigc2-img-wp img {
        width:100%;
    }

    #smal2-img-list {
        padding-top:10px;
    }
    #smal2-img-list .itm {
        display:inline-block;
        float:left;
        margin-right:10px;
        background-position: center center;
        background-repeat: no-repeat;
        background-size: cover;
        width:96px;
        height:72px;
        box-sizing: border-box;
        opacity:.5;
    }

    #smal2-img-list .itm.last {
        margin-right:0;
    }
    #smal2-img-list .itm.selected {
        border:4px solid #478bd2;
        opacity: 1;
    }
    #smal2-img-list .itm:hover {
        opacity:1;
    }
    #crni-tt {
        font-size: 34px;
        margin-bottom:20px;
        display:block;
    }
    .caro-tt {
        color:#999;
        margin-bottom:10px;
        font-size:14px;
    }
    .data-ul {
        margin:0;
        padding:0;
        list-style: none;
    }
    .data-ul li {
        dispaly:block;
        padding:8px 20px;
        font-size: 16px;
    }
    .data-ul li:nth-child(odd) {
        background:#F0F0F0;
    }
    .data-ul li .col {
        color:#aaa;
        display:inline-block;
        width:160px;
    }
    .caro-detail {
        font-size:16px;
        line-height:30px;
    }
    .caro-detail .gltw-img {
        margin-bottom:20px;
    }

    .rela-cas, .prod-rela-cas {
        display:block;
        height:150px;
        width:250px;
        background-position: center center;
        background-repeat: no-repeat;
        background-size: cover;
        margin-right:20px;
        float:left;
        margin-bottom:50px;
        position: relative;
    }
    .prod-rela-cas {
        margin-right:17.5px;
        width:200px;
    }
    .rela-cas.even {
        margin-right:0;
    }
    .prod-rela-cas.last {
        margin-right: 0;
    }
    .rela-cas span, .prod-rela-cas span {
        display:block;
        width:100%;
        height:24px;
        line-height:24px;
        bottom:-32px;
        position:absolute;
        left:0;
        text-align: center;
        font-size: 16px;
        color:#333;
        overflow: hidden;
    }
</style>
<div class="container breadc">
    <div class="row">
        <div class="col-xs-12">
            <a href="/">首页</a>
            <span class="xsplt">/</span>
            <a href="/category/<?php echo $this->category_id ?>"><?php echo $this->category ?></a>
            <span class="xsplt">/</span>
            <span class="xsexp"><?php echo $this->model->name ?></span>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <a href="#" id="bigc2-img-wp">
                <img id="big-photo" src="<?php echo $this->first_photo?>" />
            </a>
            <div id="smal2-img-list">
                <?php foreach ($this->photo as $p):?>
                    <a href="javascript:void(0)" style="background-image:url(<?php echo $p ?>);" class="itm last small-photo"></a>
                <?php endforeach;?>
            </div>
        </div>
        <div class="col-xs-6">
            <a href="#" id="crni-tt"><?php echo $this->model->name ?></a>
            <div>
                <p class="caro-tt">数据说明</p>
                <ul class="data-ul">
                    <li>
                        <span class="col">宽度：</span>
                        <span><?php echo $this->model->width ?></span>
                    </li>
                    <li>
                        <span class="col">厚度：</span>
                        <span><?php echo $this->model->thickness ?></span>
                    </li>
                    <li>
                        <span class="col">长度：</span>
                        <span><?php echo $this->model->height ?></span>
                    </li>
                    <li>
                        <span class="col">款式：</span>
                        <span><?php echo $this->model->style ?></span>
                    </li>
                    <li>
                        <span class="col">上/下钢板厚度：</span>
                        <span><?php echo $this->model->other_thickness ?></span>
                    </li>
                    <li>
                        <span class="col">可用芯材：</span>
                        <span><?php echo $this->model->steel_core ?></span>
                    </li>
                    <li>
                        <span class="col">侧边封钢带：</span>
                        <span><?php echo $this->model->steel_belt ?></span>
                    </li>
                </ul>
            </div>
        </div>

        <div class="clear-50"></div>

        <div class="col-xs-6">
            <p class="caro-tt">详细描述</p>
            <div class="caro-detail">
                <p>
                    <?php echo $this->model->description ?>
                </p>
            </div>
        </div>
        <div class="col-xs-6">
            <p class="caro-tt">相关案例</p>
            <div>
                <a href="#" class="rela-cas" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <!--注意：此处如果是偶数，加上一个class"even"在rela-cas后面-->
                <a href="#" class="rela-cas even" style="background-image: url(/img/l-10.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="rela-cas" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="rela-cas even" style="background-image: url(/img/l-10.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="rela-cas" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="rela-cas even" style="background-image: url(/img/l-10.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="rela-cas" style="background-image: url(/img/l-11.jpg);"><span>超级摸板房</span></a>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

<div id="themieothers">

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="mneo-title">
                    其他产品
                    <div class="cline"></div>
                </div>
            </div>
            <div class="col-xs-12">
                <!--此处最多放5个关联商品，即统一分类下其他产品-->
                <a href="#" class="prod-rela-cas" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="prod-rela-cas" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="prod-rela-cas" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <a href="#" class="prod-rela-cas" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <!-- 注意：此处如果是最后一个（第5个）加上一个class:last -->
                <a href="#" class="prod-rela-cas last" style="background-image: url(/img/l-09.jpg);"><span>超级摸板房</span></a>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".small-photo").click(function() {
            var path = $(this).css("background-image");

            $("#big-photo").attr("src", photoSmallToBig(path));
        })
    })

    function photoSmallToBig(path) {
        return  path = path.replace("url(", "").replace(")", "").replace("_160", "");
    }
</script>