<div id="tv-frame">
    <div class="board">
        <form method="post">
            <div class="title">
                <?php echo $this->title; ?>
                <a href="<?php echo $this->url(array(), 'login') ?>">我是会员，直接登录</a>
            </div>
            <div class="content">
                <div class="row">
                    <input type="text" placeholder="用户邮箱" id="email"/>
                </div>
                <div class="row">
                    <input type="text" placeholder="用户名" id="username"/>
                </div>
                <div class="row">
                    <input type="password" placeholder="登录密码" id="password"/>
                </div>
                <div class="half-row">
                    <input type="checkbox" name="is-agree" id="is-aggree"><label for="is-aggree">我已阅读并接受<a href="#">《芝士电视用户协议》</a></label>
                </div>
                <div class="row">
                    <button type="submit" id="confirm-btn">注册</button>
                </div>
            </div>
        </form>
    </div>
</div>
<style>
    #is-aggree {
        display:inline-block;
        float:left;
        margin:0 5px 0 0;
        padding:0;
    }
</style>