<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/user.js"); ?>"></script>
<div class="big-box gamerbod nmt">
    <div class="wp relative">
        <img class="ssimg" src="<?php echo $this->headimgurl ?>" />
        <div class="rdcts">
            <div class="rdcrs">
                <span><?php echo $this->nickname ?></span>
            </div>
            <div class="rdcfs">
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="big-box">
    <div class="mg-ttblk" style="background:#333;color:#FFF;border-radius:5px 5px 0 0;">
        <span class="tt" id="jijj">十二月 2015</span>
        <span class="glyphicon glyphicon-menu-left mg-ttblk-i left" id="to-last-month"></span>
        <span class="glyphicon glyphicon-menu-right mg-ttblk-i right" id="to-next-month"></span>
    </div>
    <div id="real-calendar">
        <div>

        </div>
    </div>
</div>
<div class="mg-listc">
    <div id="meet-list">

    </div>
</div>
<div id="sharing-bds">
    <img src="/img/sharing.png" />
</div>
<!--<div class="big-box transparent">-->
<!--    <button class="rowbtn">-->
<!--        <i class="glyphicon glyphicon-send"></i> 分享我的日历-->
<!--    </button>-->
<!--</div>-->
<script src="<?php echo $this->jsPath("action/share.js"); ?>"></script>
<script>
    var appid = '<?php echo $this->appid ?>';
    var proposer_id = '<?php echo $this->proposer_id ?>';
    var open_id = '<?php echo $this->user_id ?>';
    var is_share = true;
    $(document).ready(function(){

        var now = new Date();
        $('#real-calendar div').Calendar({
            'weekStart' : 1,
            'date' : now
        }).on('changeDay', function(event) {
            var load_date = event.day.valueOf() + '-' + event.month.valueOf() + '-' + event.year.valueOf();

            $('#jijj').html(load_date);

            $('day_'+ event.year.valueOf()).addClass('selected');

            var meetModel = new Meet();

            var user_id = localStorage.getItem('user_id');

            meetModel.Query(proposer_id, event.year.valueOf(), event.month.valueOf(),  event.day.valueOf());
        });
        //测试
//        localStorage.clear();

        if (open_id) {
            localStorage.setItem('user_id', open_id);
        }

        var user = new User();

        var user_id = localStorage.getItem('user_id');

        user.setUser_Id(user_id);
//        alert(window.location.href);
        if (!user.valid()) {
            wx_Login(window.location.href);
        }
        else {
            var calendar = new Calendar();

            calendar.setYear($('#day_1').attr('year'));
            calendar.setMonth($('#day_1').attr('month'));
            calendar.setUser_Id(proposer_id);

            calendar.getSchedule();
        }
    });
</script>