<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/user.js"); ?>"></script>
<div class="big-box gamerbod nmt">
    <div class="wp relative">
        <img class="ssimg" src="<?php echo $this->headimgurl ?>" />
        <div class="rdcts">
            <div class="rdcrs">
                <span><?php echo $this->ncikname ?></span>
            </div>
            <div class="rdcfs">
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="big-box">
    <div class="mg-ttblk" style="background:#333;color:#FFF;border-radius:5px 5px 0 0;">
        <span class="tt" id="jijj">十二月 2015</span>
        <span class="glyphicon glyphicon-menu-left mg-ttblk-i left" id="to-last-month"></span>
        <span class="glyphicon glyphicon-menu-right mg-ttblk-i right" id="to-next-month"></span>
    </div>
    <div id="real-calendar">
        <div>

        </div>
    </div>
</div>
<div class="big-box transparent">
    <button class="rowbtn">
        <i class="glyphicon glyphicon-send"></i> 分享我的日历
    </button>
</div>

<style>
    .act-detail-cover {
        position:fixed;
        width:100%;
        height:100%;
        background:rgba(0,0,0,.5);
        z-index:20;
        left:0;
        top:0;
    }
    .act-detail-bd {
        background:#FFF;
        position:fixed;
        z-index:21;
        left:30px;
        top:80px;
        right:30px;
        bottom:80px;
    }
    .act-detail-bd .wp {
        padding:15px;
        position:absolute;
        top:50px;
        bottom:0;
        left:0;
        right:0;
        overflow: auto;
    }
</style>
<div>
    <div class="act-detail-cover"></div>
    <div class="act-detail-bd">
        <div class="mg-ttblk absolute">
            <span class="tt" id="title">快来参加</span>
            <span class="glyphicon glyphicon-remove mg-ttblk-i right cls"></span>
        </div>
        <div class="wp">
            <div class="glacker gp">
                <p class="inp-tt">活动时间</p>
                <div class="p33i9plp label label-success">已确定时间</div>
                <div class="lbke" id="selected_date">2015年6月15日</div>
            </div>
            <div class="glacker gp">
                <p class="inp-tt">活动主题</p>
                <label class="lbke" id="meet_text">你的技能</label>
            </div>
            <div class="glacker gp">
                <p class="inp-tt">地点</p>
                <label class="lbke" id="address">暂无地址</label>
            </div>
            <div class="glacker gp">
                <p class="inp-tt">已同意参加的人</p>
                <ul class="busr-lst"></ul>
                <div class="clear"></div>
            </div>
            <div class="glacker p33comts gp">
                <p id="test-tt" class="inp-tt words-ttt">暂无留言</p>
                <div id="word-list"></div>
                <p class="inp-tt" style="margin-top:5px;">发表留言</p>
                <textarea id="word_text" class="inp-txt full"></textarea>
                <button class="rowbtn" id="word_submit">提交</button>
                <div class="clear-5"></div>
                <!--            <button class="rowbtn" style="display: none" id="letmejoin">我加入</button>-->
                <!--            <button class="rowbtn" style="display: none" id="letmeleave">我退出</button>-->
                <!--            <div class="clear-5"></div>style="display: none" style="display: none"-->
                <!--            <button class="rowbtn"  id="letmejoin">我加入</button>-->
                <button class="rowbtn red" style="display: none" id="btn_leave">我退出</button>
                <button class="rowbtn" style="display: none" id="btn_join">我加入</button>
                <div class="clear-5"></div>
                <button class="rowbtn red" style="margin-top: 50px;" id="close_meet">关闭活动</button>
            </div>
        </div>
    </div>
</div>
<script>
    var appid = '<?php echo $this->appid ?>';
    var proposer_id = '<?php echo $this->user_id ?>';

    $(document).ready(function(){

        var now = new Date();
        $('#real-calendar div').Calendar({
            'weekStart' : 1,
            'date' : now
        }).on('changeDay', function(event) {
            $('#jijj').html(event.day.valueOf() + '-' + event.month.valueOf() + '-' + event.year.valueOf());
            $('#jijj').html(load_date);

            if ($('#meet-list').attr('load_date') == load_date + "_load") {
                $('#meet-list').html('');
                $('#meet-list').attr('load_date', load_date);

                return;
            }

            $('#meet-list').attr('load_date', load_date + "_load");

            var meetModel = new Meet();

            var user_id = localStorage.getItem('user_id');

            meetModel.Query(proposer_id, event.year.valueOf(), event.month.valueOf(),  event.day.valueOf());
        });
        //测试
//        localStorage.clear();
//        var user = new User();
//
//        user.setUser_Id(openid);
//
//        if (!user.valid()) {
//            userLogin();
//        }
//        else {
            var calendar = new Calendar();
            var user_id = localStorage.getItem('user_id');

            calendar.setYear($('#day_1').attr('year'));
            calendar.setMonth($('#day_1').attr('month'));
            calendar.setUser_Id(proposer_id);

            calendar.getSchedule();
//        }
    });
</script>