<img style="position:absolute;top:-2000px;" src="<?php echo $this->headimgurl ?>">
<script src="<?php echo $this->jsPath("weixin/share.js"); ?>"></script>
<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/calendar.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/user.js"); ?>"></script>
<style>
    /*#footerbar {*/
    /*display:none !important;*/
    /*}*/
</style>
<!--<div class="mg-ttblk fixed" style="padding: 10px">-->
<!--    <!-- 此处最多显示8个汉字 -->-->
<!--    <span class="tt" id="title">云步客</span>-->
<!--    <span class="glyphicon glyphicon-chevron-left mg-ttblk-i left" id="pge-cover-back"></span>-->
<!--    <span class="bak-tlable">返回<span>-->
<!--    <i id="btn_share" class="glyphicon glyphicon-share share-the-day"></i>-->
<!--</div>-->
<div class="cbook-title-x1">云步客</div>
<div class="big-box gamerbod nmt" style="padding: 15px;margin-top:65px;">
        <img class="ssimg" style="float:left" src="<?php echo $this->headimgurl ?>" />
        <div class="rdcts">
            <div class="rdcrs">
                <span><?php echo $this->nickname ?></span>
            </div>
            <div class="rdcfs">
            </div>
        </div>
        <div class="clear"></div>
</div>
<div class="big-box">
    <div class="mg-ttblk" style="background:#333;color:#FFF;border-radius:5px 5px 0 0;">
        <span class="tt" id="jijj"></span>
        <span class="glyphicon glyphicon-menu-left mg-ttblk-i left" id="to-last-month"></span>
        <span class="glyphicon glyphicon-menu-right mg-ttblk-i right" id="to-next-month"></span>
    </div>
    <div id="real-calendar">
        <div>

        </div>
    </div>
</div>
<div class="mg-listc">
    <div id="meet-list">

    </div>
</div>
<script src="<?php echo $this->jsPath("action/common.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/share.js"); ?>"></script>
<script>
    document.title = '<?php echo $this->nickname?>' + "日程安排";
    var appid = '<?php echo $this->appid ?>';
    var share_id = '<?php echo $this->proposer_id ?>';
    var meet_day = '<?php echo $this->day ?>';
    var curDate = '<?php echo $this->date ?>';
    var cur_meet_id = '<?php echo $this->meet_id ?>';
    var is_share = false;
    var users_id = "";
    var proposer_id = "";
    //分享人id
    var share_id = "";

    $(document).ready(function(){
        var now = new Date();

        $('#real-calendar div').Calendar({
            'weekStart' : 1,
            'date' : now
        }).on('changeDay', function(event) {
            var load_date = event.day.valueOf() + '-' + event.month.valueOf() + '-' + event.year.valueOf();

//            $('#jijj').html(load_date);
            var meetModel = new Meet();

            var user_id = localStorage.getItem('user_id');

            meetModel.Query(share_id, event.year.valueOf(), event.month.valueOf(),  event.day.valueOf());
        });

        var tmp_month = now.getMonth() + 1;

        $('#jijj').html(now.getFullYear() + '年' + tmp_month + '月');

        if (meet_day) {
            $('#day_'+ meet_day).addClass('selected');

            var meetModel = new Meet();

            var user_id = localStorage.getItem('user_id');
            var strDate = curDate.split('-');

            meetModel.Query(share_id, strDate[0], numDateCheck(strDate[1]),  numDateCheck(strDate[2]));
        }

        var user_id = localStorage.getItem('user_id');

        if (!user_id) {
            wx_Login(window.location.href);
        }
        else {
            localStorage.setItem('schedule_user_id', proposer_id);

            getSchedule();
            //初始化过期日历样式
            initPassCalendar(now.getFullYear(), now.getMonth() + 1);
        }
    });
</script>