<div id="tv-frame">
    <div style="text-align:center;margin:80px 0 50px 0;">
        <img src="/img/logo-big.png" />
    </div>
    <div style="text-align:center;margin-bottom:50px;">
        <img src="/img/slogan.png" width="450"/>
    </div>
    <div class="bdrow">
        <p>立刻订阅芝士电视，精彩抢先看！</p>
    </div>
    <form method="post" id="validate-form">
        <div class="bdrow">
            <input type="text" autocomplete="off" placeholder="用户邮箱" id="email" name="email" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
        </div>
        <div class="bdrow">
            <button type="submit" id="confirm-btn">发送邮件</button>
        </div>
    </form>
</div>
<style>
    #tv-header {
        display:none;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        $('#tv-header').remove();
        $('#validate-form').validate({
            rules: {
                "email": {
                    required: true,
                    email: true
                }
            }
        });
    });
</script>