<script src="<?php echo $this->jsPath("action/success.js"); ?>"></script>
<div class="big-box">
    <div class="wp">
        <div id="pgx1">
            <img width="80" src="/img/raster.png" />
            <div class="clear-15"></div>
            <p id="pgx2">您已成功创建新活动</p>
            <a href="#" id="pgx3"><?php echo $this->meet_text ?></a>
        </div>
        <div id="pgx4">
            <button id="share" class="rowbtn">分享给小伙伴们</button>
            <div class="clear-5"></div>
            <button id="myIndex" class="rowbtn">也可以在“我的主页”查看</button>
        </div>
    </div>
</div>
<div id="sharing-bds">
    <img src="/img/sharing.png" />
</div>
<style>
    #pgx1 {
        text-align:center;padding:20px 0;
    }
    #pgx2 {
        margin-bottom:0;
    }
    #pgx3 {
        font-size: 20px;margin-bottom:5px;display:inline-block;
    }
    #pgx4 {
        padding-bottom:25px;
    }
</style>
<script type="text/javascript">
    var meet_id = '<?php echo $this->meet_id ?>';
    var view_type = '<?php echo $this->view_type ?>';
</script>