<!--
    作者：vincedotnet@hotmail.com
    时间：2015-05-28
    描述：view的内部代码
-->
<style>
    .inp-tt {
        color:#aaa;
        font-size:14px;
    }
    .lbke {
        font-size:16px;
        font-weight: normal;
    }
    .glacker {
        border-bottom:1px solid #E2E2E2;
        padding-bottom:10px;
    }
</style>
<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/meet_view.js"); ?>"></script>
<div class="mg-ttblk fixed">
    <!-- 此处最多显示8个汉字 -->
    <span class="tt" id="title"></span>
    <span class="glyphicon glyphicon-chevron-left mg-ttblk-i left" id="pge-cover-back"></span>
    <button class="rowbtn" style="display: none" id="letmejoin">我加入</button>
    <button class="rowbtn" style="display: none" id="letmeleave">我退出</button>
</div>
<div class="big-box" style="margin-top:65px;">
    <div class="big-box gamerbod" style="display: none">
        <div class="wp relative">
            <img class="ssimg" src="http://tp2.sinaimg.cn/1764222885/50/5714301852/1" />
            <div class="rdcts">
                <div class="rdcrs">
                    <span>张三三三</span><span class="rdcps">发起人</span>
                </div>
                <div class="rdcfs">
                    发起于 2015年6月14日
                </div>
            </div>
            <button class="rdcym">TA的日程</button>
            <div class="clear"></div>
        </div>
    </div>
    <div class="wp">
        <div class="glacker">
            <p class="inp-tt">活动时间</p>
            <div class="p33i9plp label label-success">已确定时间</div>
            <div class="lbke" id="selected_date"></div>
        </div>
        <div class="glacker">
            <p class="inp-tt">活动主题</p>
            <label class="lbke" id="meet_text"></label>
        </div>
        <div class="glacker">
            <p class="inp-tt">地点</p>
            <label class="lbke" id="address"></label>
        </div>

<!--        <div class="glacker">-->
<!--            <p class="inp-tt">详细描述</p>-->
            <label class="lbke" style="display: none" id="remark"></label>
<!--        </div>-->

        <div class="glacker">
            <p class="inp-tt">已同意参加的人</p>
            <ul class="busr-lst">
            </ul>
            <div class="clear"></div>
        </div>
        <div class="glacker p33comts">
            <p class="inp-tt">评论</p>
            <div id="word-list">

            </div>
            <p class="inp-tt" style="margin-top:5px;">发表留言</p>
            <textarea id="word_text" class="inp-txt full"></textarea>
            <button class="rowbtn" id="word_submit">提交</button>
            <div class="clear-5"></div>
            <button class="rowbtn" style="display: none" id="close_meet">关闭活动</button>
        </div>
    </div>
</div>
<!--
    作者：vincedotnet@hotmail.com
    时间：2015-06-01
    描述：footerbar 不在该页显示，所以要加入这个style隐藏footerbar
-->
<style>
    #footerbar {
        display:none !important;
    }
</style>
<script type="text/javascript">
    var appid = '<?php echo $this->appid ?>';
    var openid = '<?php echo $this->openid ?>';
    //初始化meet_id
    var meet_id = '<?php echo $this->meet_id ?>';
    var proposer_id = '<?php echo $this->proposer_id ?>';
    var users_id = '<?php echo $this->users_id ?>';
    var user_id = '<?php echo $this->user_id ?>'
</script>