<!--
    作者：vincedotnet@hotmail.com
    时间：2015-05-28
    描述：view的内部代码
-->
<style>
    .inp-tt {
        color:#aaa;
        font-size:14px;
    }
    .lbke {
        font-size:16px;
        font-weight: normal;
    }
    .glacker {
        border-bottom:1px solid #E2E2E2;
        padding-bottom:10px;
    }
</style>
<div class="mg-ttblk fixed">
    <!-- 此处最多显示8个汉字 -->
    <span class="tt">吃烧烤吧吃烧烤吧 ...</span>
    <span class="glyphicon glyphicon-chevron-left mg-ttblk-i left" id="pge-cover-back"></span>
    <button class="rowbtn" id="letmejoin">我加入</button>
</div>
<div class="big-box" style="margin-top:65px;">
    <div class="wp">
        <div class="glacker">
            <p class="inp-tt">活动主题</p>
            <label class="lbke">吃烧烤吧吃烧烤吧吃烧烤吧</label>
        </div>
        <div class="glacker">
            <p class="inp-tt">活动时间</p>
            <div class="p33i9plp label label-success">已确定时间</div>
            <div class="lbke">2015年5月10日</div>
        </div>

        <div class="glacker">
            <p class="inp-tt">地点</p>
            <label class="lbke">江汉路步行街</label>
        </div>

        <div class="glacker">
            <p class="inp-tt">详细描述</p>
            <label class="lbke">今天不醉不归，不许开车，不许带老婆，不许带小孩，不许带爸爸妈妈...</label>
        </div>

        <div class="glacker">
            <p class="inp-tt">已同意参加的人</p>
            <ul class="busr-lst">
                <li>
                    <img src="https://d3ui957tjb5bqd.cloudfront.net/images/users/21/216/216361/avatar-75-75.jpg?1431794597"/>
                </li>
                <li>
                    <img src="https://d3ui957tjb5bqd.cloudfront.net/images/users/78/785/785751/avatar-50-50.jpg?1429437610"/>
                </li>
                <li>
                    <img src="https://d13yacurqjgara.cloudfront.net/users/11867/avatars/mini/95017d34c19948a322f660a5e4e6f6ae.jpg?1419025083"/>
                </li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="glacker p33comts">
            <p class="inp-tt">评论</p>
            <div>
                <div class="itm">
                    <div>
                        <img class="uxer" src="https://d3ui957tjb5bqd.cloudfront.net/images/users/78/785/785751/avatar-50-50.jpg?1429437610" />
                        <span class="uune">愤怒的小马</span>
                        <span class="untme">2015年1月10日 15:12</span>
                    </div>
                    <div class="ctxx">
                        具有其自己的语法规则，他的命名是由"@keyframes"开头，后面紧接着是这个“动画的名称”加上一对花括号“{}”，括号中就是一些不同时间段样式
                    </div>
                </div>
                <div class="itm">
                    <div>
                        <img class="uxer" src="https://d3ui957tjb5bqd.cloudfront.net/images/users/78/785/785751/avatar-50-50.jpg?1429437610" />
                        <span class="uune">愤怒的小马</span>
                        <span class="untme">2015年1月10日 15:12</span>
                    </div>
                    <div class="ctxx">
                        具有其自己的语法规则，他的命名是由"@keyframes"开头，后面紧接着是这个“动画的名称”加上一对花括号“{}”，括号中就是一些不同时间段样式
                    </div>
                </div>
                <div class="itm">
                    <div>
                        <img class="uxer" src="https://d3ui957tjb5bqd.cloudfront.net/images/users/78/785/785751/avatar-50-50.jpg?1429437610" />
                        <span class="uune">愤怒的小马</span>
                        <span class="untme">2015年1月10日 15:12</span>
                    </div>
                    <div class="ctxx">
                        具有其自己的语法规则，他的命名是由"@keyframes"开头，后面紧接着是这个“动画的名称”加上一对花括号“{}”，括号中就是一些不同时间段样式
                    </div>
                </div>
            </div>
            <p class="inp-tt" style="margin-top:5px;">发表留言</p>
            <textarea class="inp-txt full"></textarea>
            <button class="rowbtn">提交</button>
        </div>
    </div>
</div>
<!--
    作者：vincedotnet@hotmail.com
    时间：2015-06-01
    描述：footerbar 不在该页显示，所以要加入这个style隐藏footerbar
-->
<style>
    #footerbar {
        display:none !important;
    }
</style>