<!--
        	作者：vincedotnet@hotmail.com
        	时间：2015-05-28
        	描述：view的内部代码
        -->
<style>
    .inp-tt {
        color:#aaa;
        font-size:14px;
    }
    .lbke {
        font-size:16px;
        font-weight: normal;
    }
    .glacker {
        border-bottom:1px solid #E2E2E2;
        padding-bottom:10px;
    }
</style>
<script src="<?php echo $this->jsPath("weixin/weixin_user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/meet.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/word.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/meet_vote.js"); ?>"></script>
<div class="mg-ttblk fixed">
    <!-- 此处最多显示8个汉字 -->
    <span class="tt" id="title"></span>
    <span class="glyphicon glyphicon-chevron-left mg-ttblk-i left" id="pge-cover-back"></span>
    <button class="rowbtn" style="display: none" id="letmejoin">我加入</button>
    <button class="rowbtn" style="display: none" id="letmeleave">我退出</button>
</div>
<div class="big-box" style="margin-top:65px;">
    <div id="proposer_info" class="big-box gamerbod" style="display: none">
        <div class="wp relative">
            <img id="headimgurl" class="ssimg" src="<?php echo $this->headimgurl ?>" />
            <div class="rdcts">
                <div class="rdcrs">
                    <span id="nickname"><?php echo $this->nickname ?></span><span class="rdcps"></span>
                </div>
                <div class="rdcfs" id="create_date">
                </div>
            </div>
            <button class="rdcym" id="master_schedule">TA的日程</button>
            <div class="clear"></div>
        </div>
    </div>
    <div class="wp">
        <div class="glacker">
            <p class="inp-tt">活动时间</p>
            <div class="p33i9plp label label-warning">投票中</div>
            <div class="alttimect">
                <div class="l" id="start_date">

                </div>
                <div class="m">至</div>
                <div class="r" id="end_date">

                </div>
                <div class="clear"></div>
            </div>
            <div>
                <div class="p3micill">
                    <p class="tfice">
                        <span class="t1">我来投票</span>
                        <span class="arrow-caret"></span>
                    </p>
                    <div class="p3icej">
                        <div class="itm">
                            <p>首选时间</p>
                            <input id="first_date" type="date" />
                        </div>
                        <div class="itm">
                            <p>次选时间</p>
                            <input id="second_date" type="date" />
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="p3jnid">
                        <button class="rowbtn" id="submit-vote" style="display: none">活动时间投票(参加活动)</button>
                    </div>
                    <div class="p3jnid">
                        <button class="rowbtn" id="close-vote" style="display: none">计算活动时间</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="glacker">
            <p class="inp-tt">活动主题</p>
            <label class="lbke" id="meet_text"></label>
        </div>
        <div class="glacker">
            <p class="inp-tt">地点</p>
            <label class="lbke" id="address"></label>
        </div>

<!--        <div class="glacker">-->
<!--            <p class="inp-tt">详细描述</p>-->
            <label class="lbke" style="display: none" id="remark"></label>
<!--        </div>-->

        <div class="glacker">
            <p class="inp-tt">已同意参加的人</p>
            <ul class="busr-lst">
            </ul>
            <div class="clear"></div>
        </div>
        <div class="glacker p33comts">
            <p class="inp-tt">评论</p>
            <div id="word-list">

            </div>
            <p class="inp-tt" style="margin-top:5px;">发表留言</p>
            <textarea id="word_text"  class="inp-txt full"></textarea>
            <button class="rowbtn" id="word_submit">提交</button>
            <div class="clear-5"></div>
            <button class="rowbtn" style="display: none" id="close_meet">关闭活动</button>
        </div>
    </div>
</div>
<div id="sharing-bds">
    <img src="/img/sharing.png" />
</div>
<!--
    作者：vincedotnet@hotmail.com
    时间：2015-06-01
    描述：footerbar 不在该页显示，所以要加入这个style隐藏footerbar
-->
<style>
    #footerbar {
        display:none !important;
    }
</style>
<script type="text/javascript">
    document.title = "我们有新的活动啦，快来参加";
    var appid = '<?php echo $this->appid ?>';
    var openid = '<?php echo $this->openid ?>';
    //初始化meet_id
    var meet_id = '<?php echo $this->meet_id ?>';
    var proposer_id = '<?php echo $this->proposer_id ?>';
    var users_id = '<?php echo $this->users_id ?>';
//    var user_id = '<?php //echo $this->user_id ?>//'
    var vote = '<?php echo $this->vote ?>'
    var nickname = '<?php echo $this->nickname ?>';
    var headimgurl = '<?php echo $this->headimgurl ?>'
    var create_date = '<?php echo $this->create_date ?>'

//    alert(window.location.href);
</script>