<style>
    .wp {
        padding:20px;
    }
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>作者名称：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>作者描述：</label>
                <textarea class="form-control" id="description" name="description" data-toggle="popover"></textarea>
            </div>
            <div class="form-group">
                <label>作者SNS信息：</label>
                <div class="panel panel-info alert-info">
                    <div class="panel-body">
                        <?php foreach($this->snsOptions as $k=>$v ):?>
                        <div class="form-group">
                            <label><?php echo $v; ?>：</label>
                            <input type="text" class="form-control" id="sns-<?php echo $k; ?>" name="sns-<?php echo $k; ?>" data-toggle="popover" value="">
                        </div>
                        
                        <?php endforeach;?>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>作者Logo：</label>
                <div class='panel panel-info'>
                    <div id="gy-logo" class='panel-body gy-logo'>
                    </div>
                </div>
                <input type="hidden" name="logo" id="logo"/>
            </div>

            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
            
        </form>
    </div>
</div>


<script type="text/javascript">
    (function($) {
        $('.gy-logo').photoSelector({multi: false, thumbnailOnly: false});

        $('#save-btn').click(function() {
            var save = $('#gy-logo').attr('save');
            if (!save || save === '{}') {
                $('#logo').val('');
            } else {
                $('#logo').val(save);
            }
        });
    })(jQuery);
</script>