<style>
    .wp {
        padding:20px;
    }
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>作者名称：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>作者描述：</label>
                <textarea class="form-control" id="description" name="description" data-toggle="popover"></textarea>
            </div>
            <div class="form-group">
                <label>作者SNS信息：</label>
                <div class="panel panel-info alert-info">
                    <div class="panel-body">
                        <div class="form-group">
                            <label>新浪微博：</label>
                            <input type="text" class="form-control" id="sns-weibo" name="sns-weibo" data-toggle="popover" value="">
                        </div>
                        <div class="form-group">
                            <label>微信号：</label>
                            <input type="text" class="form-control" id="sns-weixin" name="sns-weixin" data-toggle="popover" value="">
                        </div>
                        <div class="form-group">
                            <label>邮箱：</label>
                            <input type="text" class="form-control" id="sns-email" name="sns-email" data-toggle="popover" value="">
                        </div>
                        <div class="form-group">
                            <label>个人博客：</label>
                            <input type="text" class="form-control" id="sns-blog" name="sns-blog" data-toggle="popover" value="">
                        </div>
                    </div>
                    <div class="panel-footer alert-info">
                        <button type="button" id="add-sns" class="btn btn-success btn-sm" data-toggle="modal" data-target="#add-sns-modal"><i class="glyphicon glyphicon-plus"></i> 添加一项</button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>作者Logo：</label>
                <div class='panel panel-info'>
                    <div id="gy-logo" class='panel-body gy-logo'>
                    </div>
                </div>
                <input type="hidden" name="logo" id="logo"/>
            </div>

            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
            
        </form>
    </div>
</div>

<div class="modal fade" id="add-sns-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary">确认添加</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
    (function($) {
        $('.gy-logo').photoSelector({multi: false, thumbnailOnly: false});

        $('#save-btn').click(function() {
            var save = $('#gy-logo').attr('save');
            if (!save || save === '{}') {
                $('#logo').val('');
            } else {
                $('#logo').val(save);
            }
        });
    })(jQuery);
</script>