<style>
    .btn-group {
        margin-top:15px;
    }
    .itm:hover {
        background:#F0F0F0;
    }
    label.xs {
        color:#aaa;
        font-size:smaller;
        margin-left:5px;
    }
</style>
<?php
$model = $this->model;
?>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="btb">
    <a id="clear-cache" class="btn btn-success" href="<?php echo $this->url(array(), 'manage-program-list') ?>">返回节目列表</a>
</div>
<div class="row">
    <?php
    $c = 0;
    ?>
    <?php foreach ($this->resource as $p): ?>
        <div class="col-md-2 itm">
            <div class="paddingbox20px relative">
                <p><?php echo $p['text'] ?></p>
                <p><?php echo $p['email'] ?></p>
                <p><?php echo $p['time_at'] ?></p>
                <p><?php echo $p['create_at'] ?></p>
                <div class="btn-group">
                    <?php if ($p["hot"] == 0): ?>
                        <button type="button" class="btn btn-danger btn-sm set-hot">设为热点</button>
                    <?php else: ?>
                        <button type="button" class="btn btn-danger btn-sm unset-hot">取消热点</button>
                    <?php endif; ?>
                    <button type="button" class="btn btn-danger btn-sm remove-comment">删除</button>
                </div>
                <input type="hidden" class="tmp" value="<?php echo $p['id'] ?>"/>
            </div>
        </div>
        <?php $c ++; ?>
        <?php if ($c % 6 == 0): ?>
            <div class="clearfix"></div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<div class="row">
    <div class="col-md-12 text-center">
        <?php echo $this->partial('manage/partials/_paginator_bar.phtml', array('current_page_no' => $this->paginator->getCurrentPageNumber(), 'page_count' => $this->paginator->count(), 'route_name' => 'manage-keyword-list')); ?>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.remove-comment').click(function() {
            removeObject($(this), '<?php echo $this->url(array(), 'manage-comments-remove') ?>');
        });
        
        $('.set-hot').click(function() {
            removeObject($(this), '<?php echo $this->url(array(), 'manage-comments-set-hot') ?>');
        });
        
        $('.unset-hot').click(function() {
            removeObject($(this), '<?php echo $this->url(array(), 'manage-comments-unset-hot') ?>');
        });
    })(jQuery);
</script>
