<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>分类名称：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="<?php echo $this->model->name ?>">
            </div>
            <div class="form-group">
                <label>分类描述：</label>
                <input type="text" class="form-control" id="description" name="description" data-toggle="popover" value="<?php echo $this->model->description ?>">
            </div>
            <div class="form-group">
                <label>专辑：</label>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php foreach ($this->specials as $special): ?>
                             <?php     
                                $checked = "";
                                $lb = "";
                                
                                foreach ($this->ownSpecials as $p) {
                                    if ($special->id == $p->id) {
                                        $checked = "checked='checked'";
                                        $lb = "label-success";

                                        break;   
                                    }
                                }                                
                            ?> 
                            <span class="label label-default <?php echo $lb ?> pull-left marginright10px marginbottom10px">
                                <input type="checkbox" name="specials[]" value="<?php echo $special->id ?>" id="<?php echo $special->id ?>" <?php echo $checked ?>> <label for="<?php echo $special->id ?>" ><?php echo $special->name ?></label>
                            </span>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('#parent').setSelectValue();
        $('#save-btn').click(function() {
        });
    })(jQuery);
</script>