<div class="row">
    <div class="col-md-4">
        <div class="intlbd">
            <h2>节目管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-program-list-home') ?>" role="button">查看所有节目 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-program-create') ?>" role="button">添加节目 »</a></p>
            <hr/>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-oss-list-home') ?>" role="button">文件列表 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-oss-create') ?>" role="button">上传文件 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>图片管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-list-home') ?>" role="button">查看所有图片 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-upload') ?>" role="button">上传图片 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-phototype-list-home') ?>" role="button">管理图片分类 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>分类管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-list-home') ?>" role="button">查看所有分类 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-create') ?>" role="button">添加分类 »</a></p>
        </div>
    </div>
</div>
<div class="row">    
    
    
    <div class="col-md-4">
        <div class="intlbd">
            <h2>品牌管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-brand-list-home') ?>" role="button">查看所有品牌 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-brand-create') ?>" role="button">添加品牌 »</a></p>
        </div>
    </div>
</div>
<style>
    .row {
        margin-bottom:30px;
    }
</style>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>
