<div class="row">
    <div class="col-md-4">
        <div class="intlbd">
            <h2>节目管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-program-list-home') ?>" role="button">查看所有节目 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-program-create') ?>" role="button">添加节目 »</a></p>
            <hr/>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-oss-list-home') ?>" role="button">多媒体文件列表 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-oss-create') ?>" role="button">上传多媒体文件 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>专辑管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-special-list-home') ?>" role="button">查看所有专辑 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-special-list-home') ?>" role="button">添加专辑 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>图片管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-list-home') ?>" role="button">查看所有图片 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-upload') ?>" role="button">上传图片 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-phototype-list-home') ?>" role="button">管理图片分类 »</a></p>
        </div>
    </div>
</div>
<div class="row">    
    
    <div class="col-md-4">
        <div class="intlbd">
            <h2>分类管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-list-home') ?>" role="button">查看所有分类 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-create') ?>" role="button">添加分类 »</a></p>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="intlbd">
            <h2>作者管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-author-list-home') ?>" role="button">查看所有作者 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-author-create') ?>" role="button">添加作者 »</a></p>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="intlbd">
            <h2>关键词管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-keyword-list-home') ?>" role="button">查看所有关键词 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-keyword-create') ?>" role="button">添加关键词 »</a></p>
        </div>
    </div>
</div>
<style>
    .row {
        margin-bottom:30px;
    }
</style>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>
