<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>关键词：</label>
                <input type="text" class="form-control" id="name" name="keycode" data-toggle="popover" value="<?php echo $this->model->keycode ?>">
            </div>
            <div class="form-group">
                <label>关联属性：</label>
                <input type="text" class="form-control" id="description" name="attributes" data-toggle="popover" value="<?php echo $this->model->attributes ?>">
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>

        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
      //  $('#parent').setSelectValue();
        $('#save-btn').click(function() {
            
        });
    })(jQuery);
</script>