<div id="content">
<div class="mblk">
    <ol class="breadcrumb">
        <li><a href="#"><i class="glyphicon glyphicon-home"></i> 后台管理</a>
        </li>
        <li><span class="lightgray">管理员</span>
        </li>
    </ol>
</div>
<div class="mblk">
<p class="mtitle">
    <span>管理员列表</span>
    <a class="btn btn-success widebtn" href="user-add.html" role="button"><i class="glyphicon glyphicon-plus-sign"></i>新增</a>
</p>

<div class="exc-tab">
<div class="exc-tab-head">
    <div class="exc-tab-fix">
        <div class="td">序号</div>
        <div class="td">用户</div>
        <div class="td">总数(要约/到场)</div>
        <div class="td">到场率</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">6.1</div>
        <div class="td">6.2</div>
        <div class="td">6.3</div>
        <div class="td">6.4</div>
        <div class="td">6.5</div>
        <div class="td">6.6</div>
        <div class="td">6.7</div>
        <div class="td">6.8</div>
        <div class="td">6.9</div>
        <div class="td">6.10</div>
        <div class="td">6.11</div>
        <div class="td">6.12</div>
        <div class="td">6.13</div>
        <div class="td">6.14</div>
        <div class="td">6.15</div>
        <div class="td">6.16</div>
        <div class="td">6.17</div>
        <div class="td">6.18</div>
    </div>
</div>
<div class="exc-tab-row">
    <div class="exc-tab-fix">
        <div class="td">1</div>
        <div class="td">时小鸿</div>
        <div class="td">100/40</div>
        <div class="td">40%</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
        <div class="td">02/138</div>
    </div>
</div>
<div class="exc-tab-row">
    <div class="exc-tab-fix">
        <div class="td">2</div>
        <div class="td">王莹曦</div>
        <div class="td">100/30</div>
        <div class="td">30%</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
        <div class="td">02/139</div>
    </div>
</div>
<div class="exc-tab-row">
    <div class="exc-tab-fix">
        <div class="td">3</div>
        <div class="td">张三</div>
        <div class="td">100/25</div>
        <div class="td">25%</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
    </div>
</div>
<div class="exc-tab-row">
    <div class="exc-tab-fix">
        <div class="td">4</div>
        <div class="td">李四</div>
        <div class="td">100/25</div>
        <div class="td">25%</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
    </div>
</div>
<div class="exc-tab-row">
    <div class="exc-tab-fix">
        <div class="td">5</div>
        <div class="td">曹操</div>
        <div class="td">100/25</div>
        <div class="td">25%</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
    </div>
</div>
<div class="exc-tab-row">
    <div class="exc-tab-fix">
        <div class="td">6</div>
        <div class="td">孙权</div>
        <div class="td">100/25</div>
        <div class="td">25%</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
    </div>
</div>
<div class="exc-tab-row">
    <div class="exc-tab-fix">
        <div class="td">7</div>
        <div class="td">刘备</div>
        <div class="td">100/25</div>
        <div class="td">25%</div>
    </div>
    <div class="exc-tab-scroll">
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
        <div class="td">02/140</div>
    </div>
</div>
</div>


<nav class="clearfix">
    <ul class="pagination pull-right">
        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="active"><a href="#">1</a>
        </li>
        <li><a href="#">2</a>
        </li>
        <li><a href="#">3</a>
        </li>
        <li><a href="#">4</a>
        </li>
        <li><a href="#">5</a>
        </li>
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
</div>
</div>