<style>
    .btn-group {
        margin-top:15px;
    }
    .itm:hover {
        background:#F0F0F0;
    }
    label.xs {
        color:#aaa;
        font-size:smaller;
        margin-left:5px;
    }
</style>
<?php
$model = $this->model;
?>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-12 marginbottom20px">
        共有安卓注册用户： <?php echo $this->count?> 人
    </div>
    <div class="row">
    <?php
    $c = 0;
    ?>
    <?php if ($this->resource): ?>
        <?php foreach ($this->resource as $p): ?>
            <div class="col-md-2">
                <div class="itm">
                    <div class="paddingbox10px relative">
                        <p><?php echo $p['date'] ?></p>
                        <p>安卓注册人数:<?php echo $p['android'] ?></p>
                        <p>总注册人数:<?php echo $p['count'] ?></p>
                    </div>
                </div>
            </div>
            <?php $c ++; ?>
            <?php if ($c % 6 == 0): ?>
                <div class="clearfix"></div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<script type="text/javascript">
   
</script>
