<style>
    .btn-group {
        margin-top:15px;
    }
    .itm:hover {
        background:#F0F0F0;
    }
    label.xs {
        color:#aaa;
        font-size:smaller;
        margin-left:5px;
    }
</style>
<?php
$model = $this->model;
?>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-12 marginbottom20px">
        共有安卓注册用户： <?php echo $this->count?> 人
    </div>
    <?php
        $c = 0;
    ?>
<script type="text/javascript">
   
</script>
