<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>video preview</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <div>
            <video width="800" height="374" autoplay>
                <source src="<?php echo $this->video ?>" type="video/mp4" />
                你浏览器不支持 video 功能
            </video>
        </div>
    </body>
</html>
