<div>
    <video id="video-control" width="800" height="374" controls>
        <source src="<?php echo $this->video ?>" type="video/mp4" />
        你浏览器不支持 video 功能
    </video>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#video-control').on('ended', function(){
            alert('ended');
        });
        
        setInterval(function(){
            console.log($('#video-control').get(0).ended);
        }, 200);
    });
</script>