<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>文件名称：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover">
            </div>
            <div class="form-group">
                <label>文件描述：</label>
                <textarea row="10" class="form-control" id="description" name="description"></textarea>
            </div>
            <div class="form-group">
                <label>OSS文件状态：</label>
                <select id="status" name="status">
                    <option value="online">在线</option>
                    <option value="offline">下线</option>
                </select>
            </div>
            <div class="form-group">
                <label>OSS文件类型：</label>
                <select id="type" name="type">
                    <option value="video">视频</option>
                    <option value="audio">音频</option>
                </select>
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>

        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>