<style>
    ul {
        margin:0;
        padding:0;
    }
    ul li {
        margin:0;
        list-style: none;

    }
    .curreny-rate {
        width:80px;
    }
    table {
        font-size:12px;
        margin:10px 0;
    }
    table td.col1, table td.col3, table td.col2, table td.col4 {
        padding:2px 0;
        width:90px;
    }
    table td.col2, table td.col4 {
        width:150px;
    }
    table td input[type='number'] {
        background: #F0F0F0;
        width: 80px;
    }
    .input-group-addon {
        width:80px;
        text-align:center;
    }
    .price {
        text-align:center;
    }

    #base-rmb {
        background:#ffff80;
        display:inline-block;
        margin:0 10px;
        width:150px;
    }
    .location-ul, .scale-ul {
        background:#EEE;
        border-radius:4px;
        margin-top:5px;
        padding:15px;
    }
    .location-ul label, .scale-ul label {
        font-weight:normal;
    }
    .location-ul li, .scale-ul li {
        float:left;
        margin:0;
        margin-right:20px;
    }
    .scale-ul li {
        margin-right: 30px;
    }
</style>
<?php
$model = $this->model;
?>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">

        <form role="form" method="post">
            <div class="form-group">
                <label>节目标题：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="<?php echo $model->name ?>">
            </div>
            <div class="form-group">
                <label>节目附标题：</label>
                <input type="text" class="form-control" id="sub_title" name="sub_title" data-toggle="popover" value="<?php echo $model->sub_title ?>">
            </div>
            <div class="form-group">
                <label>节目状态：</label>
                <select id="status" name="status" value="<?php echo $model->status ?>">
                    <option value="online" selected="selected">在线</option>
                    <option value="soldout">下线</option>
                </select>
            </div>
            <!--            <div class="form-group">
                            <label>节目图片：</label>
            <?php //if ($this->imageBroken): ?>
                                <label class="label label-danger">部分图片已被删除，无法显示，请重新设置</label>
            <?php // endif; ?>
                            <div class='panel panel-info'>
                                <div id="gy-photo" class='panel-body gy-photo'>
                                </div>
                            </div>
                            <input type="hidden" name="photo" id="photo"/>
                        </div>-->
            <div class="form-group">
                <label>描述：</label>
                <textarea row="10" class="form-control" id="description" name="description"><?php echo $model->description ?></textarea>
            </div>
            <div class="form-group">
                <label>节目时长：</label>
            </div>
            <div class="form-group">
                <input type="text" onkeyup="this.value = this.value.replace(/\D/g, '')" onafterpaste="this.value=this.value.replace(/\D/g,'')" class="form-control" id="time" name="min" data-toggle="popover" placeholder="分" style="width:80px; float: left; margin-right: 10px" value="<?php echo $this->min ?>">
                <input type="text" onkeyup="this.value = this.value.replace(/\D/g, '')" onafterpaste="this.value=this.value.replace(/\D/g,'')" class="form-control" id="time" name="sec" data-toggle="popover" placeholder="秒" style="width:80px; margin-right: 10px" value="<?php echo $this->sec ?>">
            </div>
            <div class="form-group">
                <label>关键词：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->keywords as $keyword): ?>
                    <input type="checkbox" name="keyword[]" value="<?php echo $keyword->id ?>" 
                    <?php
                        foreach ($this->model->keyword as $p) {
                            if ($keyword->id == $p->id) {
                                echo "checked='checked'";
                                
                                break;
                            }
                        }
                    ?>> <?php echo $keyword->name ?><br>
                <?php endforeach; ?>
                <?php
                    if (count($this->keywords) == 0) {
                        echo '<a href="' . $this->url(array(), "manage-keyword-list-home") . '" class="butn btn-default" target="_blank">暂时没有关键词可以关联， 现在添加</a>';
                    }
                ?>
            </div>
            <div class="form-group">
                <label>音频文件：</label>
                <?php
                $oaid = "";
                try {
                    $oaid = $this->model->oss_audio->id;
                } catch (Exception $ex) {
                    $oaid = false;
                }
                ?>
                <select id="oss_audio" name="oss_audio">
                    <option value="">无文件</option>
                    <?php foreach ($this->oss_audio as $b): ?>
                        <option value="<?php echo $b->id ?>"
                        <?php
                        if ($oaid == $b->id) {
                            echo "selected='selected'";
                        }
                        ?>>
                                    <?php echo $b->name; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label>视频文件：</label>
                <?php
                $ovid = "";
                try {
                    $ovid = $this->model->oss_video->id;
                } catch (Exception $ex) {
                    $ovid = false;
                }
                ?>
                <select id="oss_video" name="oss_video">
                    <option value="">无文件</option>
                    <?php foreach ($this->oss_video as $b): ?>
                        <option value="<?php echo $b->id ?>"
                        <?php
                        if ($ovid == $b->id) {
                            echo "selected='selected'";
                        }
                        ?>>   
                                    <?php echo $b->name ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <label>字幕：</label>
                <textarea row="10" class="form-control" id="captions" name="captions"><?php echo $model->captions ?></textarea>
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>

        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {

        $('input[data-toggle="popover"]').popover({animation: false});

        $('.gy-photo').photoSelector(false, <?php echo json_encode($this->photo) ?>);
        $('#status').setSelectValue();
        $('#oss_audio').setSelectValue();
        $('#oss_video').setSelectValue();

        //      $('.gy-photo').photoSelector(false, <?php echo json_encode($this->photo) ?>);

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });
    })(jQuery);
</script>
