<link href="/uploadify/uploadify.css" rel="stylesheet" type="text/css" />
<style>
    ul {
        margin:0;
        padding:0;
    }
    ul li {
        margin:0;
        list-style: none;

    }
    .curreny-rate {
        width:80px;
    }
    table {
        font-size:12px;
        margin:10px 0;
    }
    table td.col1, table td.col3, table td.col2, table td.col4 {
        padding:2px 0;
        width:90px;
    }
    table td.col2, table td.col4 {
        width:150px;
    }
    table td input[type='number'] {
        background: #F0F0F0;
        width: 80px;
    }
    .input-group-addon {
        width:80px;
        text-align:center;
    }
    .price {
        text-align:center;
    }

    #base-rmb {
        background:#ffff80;
        display:inline-block;
        margin:0 10px;
        width:150px;
    }
    .location-ul, .scale-ul {
        background:#EEE;
        border-radius:4px;
        margin-top:5px;
        padding:15px;
    }
    .location-ul label, .scale-ul label {
        font-weight:normal;
    }
    .location-ul li, .scale-ul li {
        float:left;
        margin:0;
        margin-right:20px;
    }
    .scale-ul li {
        margin-right: 30px;
    }
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">

        <form role="form" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label>节目标题：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>节目附标题：</label>
                <input type="text" class="form-control" id="sub_title" name="sub_title" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>节目状态：</label>
                <select id="status" name="status">
                    <option value="online" selected="selected">在线</option>
                    <option value="soldout">下线</option>
                </select>
            </div>
<!--            <div class="form-group">
                <label>节目图片：</label>
                <div class='panel panel-info'>
                    <div id="gy-photo" class='panel-body gy-photo'>
                    </div>
                </div>
                <input type="hidden" name="photo" id="photo"/>
            </div>-->
            <div class="form-group">
                <label>描述：</label>
                <textarea row="10" class="form-control" id="description" name="description"></textarea>
            </div>
            <div class="form-group">
                <label>节目时长：</label>
                <input type="text" class="form-control" id="time" name="time" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>关键词：</label>
                <?php foreach ($this->keywords as $keyword): ?>
                    <input type="checkbox" name="keywords[]" value="<?php echo $keyword->id ?>"> <?php echo $keyword->name ?><br>
                <?php endforeach; ?>
                 <?php 
                    if (count($this->keywords) == 0) {
                        echo '<a href="'.$this->url(array(), "manage-keyword-list-home").'" class="butn btn-default" target="_blank">暂时没有关键词可以关联， 现在添加</a>';
                    }    
                ?>     
            </div>
            <div class="form-group">
                <label>音频文件：</label>
                <select id="oss_audio" name="oss_audio" value="">
                    <option value="">无文件</option>
                    <?php foreach ($this->oss_audio as $b): ?>
                        <option value="<?php echo $b->id ?>"><?php echo $b->name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label>视频文件：</label>
                <select id="oss_video" name="oss_video" value="">
                    <option value="">无文件</option>
                    <?php foreach ($this->oss_video as $b): ?>
                        <option value="<?php echo $b->id ?>"><?php echo $b->name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label>作者：</label>
                <select id="author" name="author" value="">
                    <option value="">无作者</option>
                    <?php foreach ($this->author as $b): ?>
                        <option value="<?php echo $b->id ?>"><?php echo $b->name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label>字幕：</label>
                <input type="file" id="captions" name="captions">
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>

        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('input[data-toggle="popover"]').popover({animation: false});

//        $('.gy-photo').photoSelector(false, "set save here");
        $('.gy-photo').photoSelector();

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });
        
        $("#file_upload").uploadify({
            swf: '/uploadify/uploadify.swf',
            uploader: '/manage/txt/upload',
            fileTypeExts: '*.txt',
            buttonText: '选择即将上传的文件',
            auto: false,
            height: 30,
            width: 180,
            'onUploadComplete': function(file) {
            },
            'onUploadSuccess': function(file, data, response) {
                uploadifyUploadSuccess(file, data, response);
            },
            'onQueueComplete': function(queueData) {
                uploadifyQueueComplete(queueData);
            },
            'onUploadStart': function(file) {

            }
        });

        function uploadifyUploadSuccess(file, data, response) {
            var files = $('#next-lnk').attr('files');
            if (files) {
                files += "|" + data;
            } else {
                files = data;
            }
            $('#next-lnk').attr('files', files);
        }
        function uploadifyQueueComplete(queueData) {
            $('#no-success').html(queueData.uploadsSuccessful);
            $('#next-step').show();
        }

        $('#upload-all').click(function() {
            $('#file_upload').uploadify('upload', '*');
        });

        $('#cancel-all').click(function() {
            $('#file_upload').uploadify('cancel', '*');
            $('#next-step').hide();
            $('#next-lnk').attr('files', '');
        });
        $('#next-lnk').click(function() {
            var url = $(this).attr('href') + "?fs=" + $(this).attr('files');
            $(this).attr('href', url);
        });
    })(jQuery);
</script>