<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>专辑：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="<?php echo $this->model->name ?>">
            </div>
            <div class="form-group">
                <label>作者：</label>

                <select id="authorId">
                    <option value="">作者</option>
                    <?php foreach ($this->authors as $author): ?>
                        <option value="<?php echo $author->id ?>" <?php
                        if ($this->model->authorId == $author->id) {
                            echo "selected='selected'";
                        }
                        ?>>
                        <?php
                        echo $author->name;
                        ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label>分类：</label>
                <select id="categoryId" name="categoryId" value="">
                    <option value="">分类</option>
                    <?php foreach ($this->categorys as $category): ?>
                        <option value="<?php echo $category->id ?>" <?php
                            if ($this->model->categoryId == $category->id) {
                                echo "selected='selected'";
                            }
                            ?>>
                            <?php
                            echo $category->name;
                            ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <label>专辑图片：</label>
                <div class='panel panel-info'>
                    <div id="gy-photo" class='panel-body gy-photo'>
                    </div>
                </div>
                <input type="hidden" name="photo" id="photo"/>
            </div>
            <div class="form-group">
                <label>节目：</label>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php foreach ($this->programs as $program): ?>
                             <?php 
                                foreach ($this->ownProgramIds as $ownProgramId) {
                                    if ($program->id == $ownProgramId) {
                                        $checked = "checked='checked'";
                                        $lb = "label-success";

                                        break;   
                                    }
                                } 
                                
                            ?> 
                            <span class="label label-default <?php echo $lb ?> pull-left marginright10px">
                                <input type="checkbox" name="programs[]"value="<?php echo $program->id ?>" id="<?php echo $program->id ?>" <?php echo $checked ?>> <label for="<?php echo $program->id ?>" ><?php echo $program->name ?></label>
                            </span>

                        <?php endforeach; ?>
                    </div>
                </div>
            </div>


            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.gy-photo').photoSelector(false, <?php echo json_encode($this->photo) ?>);

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });
        
        $('input[name="programs[]"]').change(function(){
            $(this).closest('.label').toggleClass('label-success');
        });
    })(jQuery);
</script>