<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>专辑：</label>
                <input type="text" class="form-control" id="name" name="special_name" data-toggle="popover" value="<?php echo $this->special->special_name ?>">
            </div>
            <div class="form-group">
                <label>作者：</label>
                <!--input type="text" class="form-control" id="description" name="attributes" data-toggle="popover" value="<?php //echo $this->keyword->attributes ?>"-->
                <select id="author_id">
                    <option value="">作者</option>
                    <?php foreach ($this->authors as $author): ?>
                        <option value="<?php echo $author->id ?>">
                            <?php
                                echo $author->name;
                            ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label>专辑图片：</label>
                <div class='panel panel-info'>
                    <div id="gy-photo" class='panel-body gy-photo'>
                    </div>
                </div>
                <input type="hidden" name="photo" id="photo"/>
            </div>
            <div class="form-group">
                <?php foreach ($this->programs as $program): ?>
                    <input type="checkbox" name="programs" value="<?php echo $program->id ?>"> <?php echo $program->name ?><br>
                <?php endforeach; ?>
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
      //  $('#parent').setSelectValue();
        $('#save-btn').click(function() {
            
        });
    })(jQuery);
</script>