<style>
    .btn-group {
        margin-top:15px;
    }
    .itm:hover {
        background:#F0F0F0;
    }
    label.xs {
        color:#aaa;
        font-size:smaller;
        margin-left:5px;
    }
</style>
<?php
$model = $this->model;
?>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="btb">
    <a id="clear-cache" class="btn btn-success" href="<?php echo $this->url(array(), 'manage-special-create') ?>">新建专辑</a>
</div>
<div class="row">
    <?php
    $c = 0;
    ?>
    <?php foreach ($this->resource as $p): ?>
        <div class="col-md-2 itm">
            <div class="paddingbox20px relative">
                <p><?php echo $p['name'] ?> </p>
                <div class="btn-group">
                    <a type="button" href="<?php echo $this->url(array(id => $p["id"]), 'manage-special-save') ?>" class="btn btn-info btn-sm">编辑</a>
                    <button type="button" class="btn btn-danger btn-sm remove-special">删除</button>
                </div>
                <input type="hidden" class="tmp" value="<?php echo $p['id'] ?>"/>
            </div>
        </div>
        <?php $c ++; ?>
        <?php if ($c % 6 == 0): ?>
            <div class="clearfix"></div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<div class="row">
    <div class="col-md-12 text-center">
        <?php echo $this->partial('manage/partials/_paginator_bar.phtml', array('current_page_no' => $this->paginator->getCurrentPageNumber(), 'page_count' => $this->paginator->count(), 'route_name' => 'manage-special-list')); ?>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.remove-special').click(function() {
            removeObject($(this), '<?php echo $this->url(array(), 'manage-special-remove') ?>');
        });
    })(jQuery);
</script>
