<style>
    .btn-group {
        margin-top:15px;
    }
    .itm:hover {
        background:#F0F0F0;
    }
    label.xs {
        color:#aaa;
        font-size:smaller;
        margin-left:5px;
    }
</style>
<?php
$model = $this->model;
?>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="btb">
</div>
<div class="row">
    <?php
        $c = 0;
    ?>
    <?php foreach ($this->resource as $p): ?>
        <div class="col-md-2 itm">
            <div class="paddingbox20px relative">
                <p>邮箱:<?php echo $p['email'];  ?></p>
                <p>用户名:<?php echo $p['username'];  ?></p>
                <p>性别:<?php echo $p['gender'];  ?></p>
                <p>出生年份:<?php echo $p['age'];  ?></p>
                <p>注册时间:<?php echo $p['ceated_date'];  ?></p>
                <div class="btn-group">
                    <button type="button" class="btn btn-danger btn-sm " onclick="vipfix('<?php echo $p["id"]; ?>')">修复数据</button>
                </div>
                <input type="hidden" class="tmp" value="<?php echo $p['id'] ?>"/>
            </div>
        </div>
        <?php $c ++; ?>
        <?php if ($c % 6 == 0): ?>
            <div class="clearfix"></div><div class="clear"></div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    function vipfix(id) {
        var url = '/manage/vip/fix';
        var data = {id: id};

        $.ajax({
            url: url,
            dataType: 'json',
            data: data,
            type: 'POST',
            success: function(response) {
                if (response) {
                    if (response.code == '200')
                        location.reload();
                    else
                        alert(response.data);
                } else {
                    alert('设置失败');
                }
            }
        });
    }
</script>
