<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <title></title>
    <link rel="stylesheet" href="<?php echo $this->cssPath("bootcss.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("global.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("datepicker.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("shake-animate.css"); ?>">
    <script src="<?php echo $this->jsPath("jquery-1.11.2.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("bootstrap.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("bootstrap.calendar.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("global.js"); ?>"></script>
</head>
<body ontouchstart="">
    <?php echo $this->layout()->content; ?>
    <!--
        	作者：vincedotnet@hotmail.com
        	时间：2015-06-01
        	描述：以下为页脚，放到layout母版中
        -->
    <div id="footerbar">
        <div class="itm selected">
            <i class="glyphicon glyphicon-home"></i>
            <div class="botlin"></div>
        </div>
        <div class="itm md">
            <i class="glyphicon glyphicon-user"></i>
            <div class="botlin"></div>
        </div>
        <div class="itm">
            <i class="glyphicon glyphicon-plus"></i>
            <div class="botlin"></div>
        </div>
    </div>
    <div style="display: none">
        <div class="itm words">
            <div>
                <img class="uxer" src="https://d3ui957tjb5bqd.cloudfront.net/images/users/78/785/785751/avatar-50-50.jpg?1429437610" />
                <span class="uune">愤怒的小马</span>
                <span class="untme">2015年1月10日 15:12</span>
            </div>
            <div class="ctxx">
                具有其自己的语法规则，他的命名是由"@keyframes"开头，后面紧接着是这个“动画的名称”加上一对花括号“{}”，括号中就是一些不同时间段样式
            </div>
        </div>
    </div>
</body>
</html>
