<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <title></title>
    <link rel="stylesheet" href="<?php echo $this->cssPath("bootcss.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("global.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("datepicker.css"); ?>">
</head>
<body ontouchstart="">
    <?php echo $this->layout()->content; ?>
    <script src="<?php echo $this->jsPath("jquery-1.11.2.js"); ?>></script>
    <script src="<?php echo $this->jsPath("bootstrap.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("bootstrap-datepicker.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("global.js"); ?>"></script>
    <script>
        $(document).ready(function(){
    //				$('#single-date').datepicker();
            $('#datepicker').datepicker();
            $("#datepicker").on("changeDate", function(event) {
                $("#my_hidden_input").val(
                    $("#datepicker").datepicker('getFormattedDate')
                )
            });

            $('#ddrg').datepicker();
        });
    </script>
</body>
</html>
