<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <title></title>
    <link rel="stylesheet" href="<?php echo $this->cssPath("bootcss.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("global.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("pop_css.css"); ?>">
    <script src="<?php echo $this->jsPath("jquery-1.11.2.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("bootstrap.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("bootstrap.calendar.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("global.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("tools/popup.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("weixin/developer.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("action/common.js"); ?>"></script>
</head>
<body ontouchstart="">
    <div id="top-bar" class="mg-ttblk fixed" style="padding: 10px">
        <!-- 此处最多显示8个汉字 -->
        <span class="tt" id="title">我的云步客</span>-->
        <span class="glyphicon glyphicon-chevron-left mg-ttblk-i left" id="pge-cover-back"></span>
        <i id="btn_share" class="glyphicon glyphicon-share share-the-day"></i>
    </div>
    <?php echo $this->layout()->content; ?>
    <button id="btn_add" class="miowobtn">+</button>
<!--    <div id="footerbar">-->
<!--        <div class="itm selected" id="btn_home" style="width: 50%">-->
<!--            <i class="glyphicon glyphicon-home"></i>-->
<!--            <div class="botlin"></div>-->
<!--        </div>-->
<!--        <div class="itm md">-->
<!--            <i class="glyphicon glyphicon-user"></i>-->
<!--            <div class="botlin"></div>-->
<!--        </div>-->
<!--        <div class="itm add-cal" id="btn_add" style="width: 50%">-->
<!--            <i class="glyphicon glyphicon-plus"></i>-->
<!--            <div class="botlin"></div>-->
<!--        </div>-->

<!--    </div>-->

    <div style="display: none">
        <div id="mg-listc" >
            <div class="mg-listc">
                <p class="meet_date"></p>
                <div id="meet-list">

                </div>
            </div>
        </div>
        <div id="meet_model" class="mg-listc-blk">
            <div class="mg-listc-ni">
                <div class='mg-listc-pd'>
                    <div class="mg-listc-btt"></div>
                    <div class="mg-listc-usrs clearfix">
                    </div>
                    <div class="glyphicon glyphicon-chevron-right mg-listc-rarr"></div>
                    <span class="let-join" style="display: none">邀您参加</span>
                </div>
            </div>
        </div>
        <div id="meet_add_model" class="mg-listc-blk">
            <div class="pad-15">
                 <button class="rowbtn mg-listc-btt" >新活动</button>
            </div>
        </div>
        <div id="word_model" class="itm words">
            <div>
                <img class="uxer" src="https://d3ui957tjb5bqd.cloudfront.net/images/users/78/785/785751/avatar-50-50.jpg?1429437610" />
                <span class="uune"></span>
                <span class="untme"></span>
            </div>
            <div class="ctxx">
            </div>
        </div>
    </div>
    <div id="sharing-bds">
        <img src="/img/sharing.png" />
    </div>

    <style>
        .act-detail-cover {
            position:fixed;
            width:100%;
            height:100%;
            background:rgba(0,0,0,.5);
            z-index:20;
            left:0;
            top:0;
        }
        .act-detail-bd {
            background:#FFF;
            position:fixed;
            z-index:21;
            left:30px;
            top:80px;
            right:30px;
            bottom:80px;
        }
        .act-detail-bd .wp {
            padding:15px;
            position:absolute;
            top:50px;
            bottom:0;
            left:0;
            right:0;
            overflow: auto;
        }
    </style>

    <div id="show-meet-view" style="display: none">
        <div class="act-detail-cover"></div>
        <div class="act-detail-bd">
            <div class="mg-ttblk absolute">
                <span class="tt" id="title">快来参加</span>
                <i id="view_meet_share" class="glyphicon glyphicon-share share-the-day"></i>
                <span class="glyphicon glyphicon-remove mg-ttblk-i right cls"></span>
            </div>
            <div class="wp">
                <div class="glacker gp">
                    <p class="inp-tt">活动时间</p>
                    <div class="p33i9plp label label-success">已确定时间</div>
                    <div class="lbke" id="selected_date"></div>
                </div>
                <div class="glacker gp">
                    <p class="inp-tt">活动主题</p>
                    <label class="lbke" id="view_meet_text"></label>
                </div>
                <div class="glacker gp">
                    <p class="inp-tt">地点</p>
                    <label class="lbke" id="view_address"></label>
                </div>

                <label class="lbke" style="display: none" id="remark"></label>

                <div class="glacker gp">
                    <p class="inp-tt">已同意参加的人</p>
                    <ul class="busr-lst">
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="glacker p33comts gp">
                    <p id="test-tt" class="inp-tt words-ttt">留言</p>
                    <div id="word-list">

                    </div>
                    <p class="inp-tt" style="margin-top:5px;">发表留言</p>
                    <textarea id="view_word_text" class="inp-txt full"></textarea>
                    <button class="rowbtn" id="view_word_submit">提交</button>
                    <div class="clear-5"></div>
                    <button class="rowbtn red" style="display: none" id="btn_view_leave">我退出</button>
                    <button class="rowbtn" style="display: none" id="btn_view_join">我加入</button>
                    <div class="clear-5"></div>
                    <button class="rowbtn red" style="display: none;margin-top:50px;" id="view_close_meet">关闭活动</button>
                </div>
            </div>
        </div>
    </div>

    <div id="show-meet-vote" style="display: none">
        <div class="act-detail-cover"></div>
        <div class="act-detail-bd">
            <div class="mg-ttblk absolute">
                <span class="tt" id="title">快来参加</span>
                <i id="view_meet_share" class="glyphicon glyphicon-share share-the-day"></i>
                <span class="glyphicon glyphicon-remove mg-ttblk-i right cls"></span>
            </div>
            <div class="wp">
                <div class="glacker gp">
                    <p class="inp-tt">活动时间</p>
                    <div class="p33i9plp label label-warning">投票中</div>
                    <div class="alttimect">
                        <div class="l" id="start_date">

                        </div>
                        <div class="m">至</div>
                        <div class="r" id="end_date">

                        </div>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <div class="p3micill">
                            <p class="tfice">
                                <span class="t1">我来投票</span>
                                <span class="arrow-caret"></span>
                            </p>
                            <div class="p3icej">
                                <div class="itm">
                                    <p>首选时间</p>
                                    <input id="first_date" type="date" />
                                </div>
                                <div class="itm">
                                    <p>次选时间</p>
                                    <input id="second_date" type="date" />
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="p3jnid">
                                <p id="ps_text" style="text-align:center; display: none">您还有没有投票的活动：</p>
                                <button class="rowbtn" id="vote_submit-vote" style="display: none">活动时间投票(参加活动)</button>
                            </div>
                            <div class="p3jnid">
                                <button class="rowbtn" id="vote_close-vote" style="display: none">计算活动时间</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="glacker gp">
                    <p class="inp-tt">活动主题</p>
                    <label class="lbke" id="vote_meet_text"></label>
                </div>
                <div class="glacker gp">
                    <p class="inp-tt">地点</p>
                    <label class="lbke" id="vote_address"></label>
                </div>

                <label class="lbke" style="display: none" id="remark"></label>

                <div class="glacker gp">
                    <p class="inp-tt">已同意参加的人</p>
                    <ul class="busr-lst">
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="glacker p33comts gp">
                    <p id="test-tt" class="inp-tt words-ttt">留言</p>
                    <div id="vote_word-list">

                    </div>
                    <p class="inp-tt" style="margin-top:5px;">发表留言</p>
                    <textarea id="vote_word_text"  class="inp-txt full"></textarea>
                    <button class="rowbtn" id="vote_word_submit">提交</button>
                    <div class="clear-5"></div>
                    <button class="rowbtn" style="display: none" id="vote_btn_join">我加入</button>
                    <button class="rowbtn red" style="display: none" id="vote_btn_leave">我退出</button>
                    <div class="clear-5"></div>
                    <button class="rowbtn red" style="display: none" id="vote_close_meet">关闭活动</button>
                </div>
            </div>
        </div>
    </div>
    <script src="<?php echo $this->jsPath("global.js"); ?>"></script>
</body>
</html>


