<!DOCTYPE html>
<html>
    <head>
        <title>芝士电视</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="<?php echo $this->cssPath("bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->cssPath("global.css"); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->cssPath("global.show.css"); ?>" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->jsPath('jquery.1.10.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('global.js'); ?>"></script>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
            <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script type="text/javascript">
            $('document').ready(function() {
                // ddl init
                var profile_txt = $('#profile-txt');
                if (profile_txt.length > 0) {
                    profile_txt.click(function() {
                        $('#tv-header-ddl').clickToggle();
                    });
                }
            });
        </script>
    </head>

    <body>

        <div id="tv">
            <div id="tv-header">
                <div class="wp clearfix">
                    <div class="clearfix" id="tv-switch">
                        <span id="tv-to-video" class="selected"><i class="ico"></i></span>
                        <span id="tv-to-audio"><i class="ico"></i></span>
                    </div>
                    <img id="tv-logo" src="../img/logo-sm.png"/>
                    <a href='javascript:void(0)' id="fullscreen" class="ico unvisiable"></a>
                    <div class="spliter" id="rt-spliter"></div>
                    <div class="pull-right" id="profile-blk">
                        <a href="javascript:void(0)" id="profile-txt"> <span>王啸</span> <i class="ico"></i> </a>
                        <a href="javascript:void(0)" id="profile-img"><img src="http://img.36tr.com/avatar/20140424/53587efbcaaf1_100100.jpg"/></a>
                    </div>
                    <div class="spliter" id="rt-spliter"></div>
                    <a href='javascript:void(0)' class="unvisiable" id="refresh"> <i class="ico"></i> 换一批 </a>

                    <ul id="tv-header-ddl" class="ddl">
                        <li>
                            <a href="#"><i class='ico profile'></i> <span class="txt">我的信息</span></a>
                        </li>
                        <li>
                            <a href="#"><i class='ico list'></i> <span class="txt">查看节目列表</span></a>
                        </li>
                        <li class="hspliter">
                            <a href="#"><i class='ico logout'></i> <span class="txt">退出登录</span></a>
                        </li>
                    </ul>
                </div>
                <div class="spliter"></div>
            </div>

            <?php echo $this->layout()->content; ?>
        </div>




        
    </body>
</html>



