<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <title>芝士电视管理系统</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="renderer" content="webkit">
        <!-- Bootstrap -->

        <link rel="stylesheet" href="<?php echo $this->cssPath("bootstrap.css"); ?>">
        <link rel="stylesheet" href="<?php echo $this->cssPath("bootstrap.theme.css"); ?>">
        <link href="<?php echo $this->cssPath("global.css"); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->cssPath("global.manage.css"); ?>" rel="stylesheet" type="text/css" />

        <script type="text/javascript" src="<?php echo $this->jsPath('jquery.1.10.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('plugin.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('global.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('share.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('qrcode.js'); ?>"></script>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
            <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- Static navbar -->
        <div class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/manage">芝士电视管理系统</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">节目 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-program-list-home') ?>">节目列表</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-program-create') ?>">添加节目</a></li>

                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">多媒体文件 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-oss-list-home') ?>">多媒体文件列表</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-oss-create') ?>">多媒体上传文件</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">专辑 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-special-list-home') ?>">专辑列表</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-special-create') ?>">添加专辑</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">图片 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-photo-list-home') ?>">图片列表</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-photo-upload') ?>">添加图片</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-phototype-list-home') ?>">管理图片分类</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">分类 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-category-list-home') ?>">分类列表</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-category-create') ?>">添加分类</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">达人 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-vip-list') ?>">所有用户</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-vip-create') ?>">添加达人</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">关键词 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-keyword-list-home') ?>">关键词列表</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-keyword-create') ?>">添加关键词</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">热点管理 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-hot-list') ?>">热点列表</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">版本 <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(), 'manage-version-list') ?>">版本列表</a></li>
                                <li><a href="<?php echo $this->url(array(), 'manage-version-create') ?>">添加版本</a></li>
                            </ul>
                        </li>
                    </ul>
                    <?php if (isset($this->me)): ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="<?php echo $this->url(array(), 'manage-logout') ?>" title="<?php echo $this->me->getUser()->email ?>">你好 管理员, 安全退出 <i class="glyphicon glyphicon-off"></i></a></li>
                        </ul>
                    <?php else: ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="<?php echo $this->url(array(), 'manage-login') ?>">登录</a></li>
                        </ul>

                    <?php endif; ?>

                </div><!--/.nav-collapse -->
            </div>
        </div>


        <div class="container">
            <?php echo $this->layout()->content; ?>
        </div> <!-- /container -->
        <div class='marginbottom50px'>

        </div>
        <script type="text/javascript">
            $(document).ready(function() {

            });
        </script>
    </body>
</html>