<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <title></title>
    <link rel="stylesheet" href="<?php echo $this->cssPath("bootcss.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("global.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("pop_css.css"); ?>">
    <script src="<?php echo $this->jsPath("jquery-1.11.2.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("bootstrap.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("bootstrap.calendar.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("global.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("tools/popup.js"); ?>"></script>
    <script src="<?php echo $this->jsPath("weixin/developer.js"); ?>"></script>
</head>

<body ontouchstart="">
    <?php echo $this->layout()->content; ?>
</body>

</html>