<?php
$user = null;
$username = "";
if ($this->me) {
    $user = $this->me->getUser();
    $username = $user->username;
}
?>

<!DOCTYPE html>
<html>
    <head>
        <title>芝士电视</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <!--[if (lte IE 9) ]> <script type="text/javascript">location.href="<?php echo $this->url(array(), 'upgrade') ?>";</script> <![endif]-->
        <link href="<?php echo $this->cssPath("bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->cssPath("global.css"); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->cssPath("global.show.css"); ?>" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->jsPath('jquery.1.10.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('validation.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('global.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->jsPath('plugin.js'); ?>"></script>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
            <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <script type="text/javascript">
            $('document').ready(function() {
            });
        </script>
        <style>
            #tv {
                position:relative;
            }
        </style>
    </head>

    <body>
        <div>

        </div>
        <div id="tv">
            <div id='tv-normal-header' style='text-align:center;padding-top:30px;'>
                <a href='#'><img src='/img/logo.png'/></a>
                <?php if ($this->me): ?>
                    <a href="<?php echo $this->url(array(), 'show-play') ?>"class="btn" style="position:absolute;right:30px;">看电视</a>
                <?php endif; ?>
            </div>
            <?php echo $this->layout()->content; ?>

        </div>
        <div id="icp">
            京ICP备 12031816
        </div>

    </body>
</html>



