<div id="tv-frame">
    <div class="board">
        <div class="title">
            登录芝士电视
            <a href="#">10秒注册</a>
        </div>
        <div class="content">
            <div class="row">
                <input type="text" placeholder="用户邮箱" id="email"/>
            </div>
            <div class="row">
                <input type="password" placeholder="登录密码" id="password"/>
            </div>
            <div class="row">
                <button type="button" id="confirm-btn">登录</button>
            </div>
        </div>
        <div class="bottom">
            <a href="#">忘记密码？</a>
        </div>
    </div>
</div>