<div id="tv-frame">
    <div class="board">
        <div class="title">
            修改密码
        </div>
        <div class="content">
            <div class="row">
                <input type="password" placeholder="当前密码" id="password"/>
            </div>
            <div class="row">
                <input type="password" placeholder="新密码" id="new-password"/>
            </div>
            <div class="row">
                <input type="password" placeholder="再次输入密码" id="re-password"/>
            </div>

            <div class="row">
                <button type="button" id="confirm-btn">确认修改</button>
            </div>
        </div>
    </div>
</div>