<div id="tv-frame">
    <div class="board">
        <div class="title">
            修改密码
        </div>
        <div class="content">
            <form id="validate-form">
                <div class="row">
                    <input type="password" placeholder="当前密码" id="password" name="password" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
                </div>
                <div class="row">
                    <input type="password" placeholder="新密码" id="new-password" name="new-password" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
                </div>
                <div class="row">
                    <input type="password" placeholder="再次输入密码" id="re-password" name="re-password" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
                </div>

                <div class="row">
                    <button type="submit" id="confirm-btn">确认修改</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#validate-form").validate({
        rules: {
            "password": {
                required: true,
                minlength: 6
            },
            "new-password": {
                required: true,
                minlength: 6
            },
            "re-password": {
                equalTo: "#new-password"
            }
        },
        messages: {
        }
    });
</script>