<style>
    #xos {
        font-size:25px;
        padding-bottom: 100px;
        padding-top:100px;
    }
    #sod {
        border-bottom:1px solid rgba(255,255,255,0.1);
        box-shadow: 0 1px 0 rgba(0,0,0,0.3);
        margin-bottom:20px;
        padding-bottom:20px;
    }
</style>

<div id="xos" class="">
    <div id="sod" class="text-center">
        抱歉，未找到该页面
    </div>
    <div class="text-center">
        <a class="btn btn-sm" href="<?php echo $this->url(array(), 'home') ?>">返回首页</a>
    </div>
    
</div>
