<div id="tv-footer">
    <div id="tv-listbar">
        <div id="tv-listbar-title">
            <a href="javascript:void(0)" id="tv-author-img"><img id="logo" src="http://img.36tr.com/avatar/20140424/53587efbcaaf1_100100.jpg"/></a>
            <div class="wp">
                <div id="tvidx02">
                    <p id="tv-special-name">
                        刘德华2014新专辑
                    </p>
                    <span id="tvidx01">By </span><a id="tv-author-name" href="javascript:void(0)">刘德华</a>
                </div>
                <button class="empty-btn close-btn" id="tv-listbar-close"></button>
            </div>
        </div>
        <div id="tv-listbar-content">
            <ul class="itm">
                <li class="col col1">
                    <i class="ico play"></i>
                </li>
                <li class="col col2">
                    Enter Sandman
                </li>
                <li class="col col3">
                    05:39
                </li>
            </ul>
            <ul class="itm alt">
                <li class="col col1">
                    <i class="ico null"></i>
                </li>
                <li class="col col2">
                    Value of true
                </li>
                <li class="col col3">
                    12:11
                </li>
            </ul>
            <ul class="itm">
                <li class="col col1">
                    <i class="ico null"></i>
                </li>
                <li class="col col2">
                    Element
                </li>
                <li class="col col3">
                    02:40
                </li>
            </ul>
            <ul class="itm alt selected">
                <li class="col col1">
                    <i class="ico null"></i>
                </li>
                <li class="col col2">
                    Current Animation
                </li>
                <li class="col col3">
                    04:10
                </li>
            </ul>
            <ul class="itm">
                <li class="col col1">
                    <i class="ico"></i>
                </li>
                <li class="col col2">
                    Nothing else matter
                </li>
                <li class="col col3">
                    07:12
                </li>
            </ul>
            <ul class="itm alt">
                <li class="col col1">
                    <i class="ico null"></i>
                </li>
                <li class="col col2">
                    Whether to remove
                </li>
                <li class="col col3">
                    01:09
                </li>
            </ul>
            <ul class="itm">
                <li class="col col1">
                    <i class="ico null"></i>
                </li>
                <li class="col col2">
                    Queued
                </li>
                <li class="col col3">
                    00:49
                </li>
            </ul>
            <ul class="itm alt">
                <li class="col col1">
                    <i class="ico null"></i>
                </li>
                <li class="col col2">
                    South Single
                </li>
                <li class="col col3">
                    15:21
                </li>
            </ul>
            <ul class="itm">
                <li class="col col1">
                    <i class="ico null"></i>
                </li>
                <li class="col col2">
                    Orion
                </li>
                <li class="col col3">
                    03:32
                </li>
            </ul>
        </div>
    </div>
    <div id="tv-footer-ltbar">
        <div class="wp">
            <button class="ico" id="prev" class="pull-left"></button>
            <button class="ico" id="play" class="pull-left"></button>
            <button class="ico" id="pause" class="pull-left"></button>
            <button class="ico" id="next" class="pull-left"></button>
        </div>
    </div>
    <div id="tv-footer-rtbar">
        <div class="wp">
            <div id="volume-ctrl" class="pull-left">
                <button id="volume-speaker" class="ico pull-left"></button>
                <div id="volume-holder" class="pull-left">
                    <div id="volume-in"></div>
                </div>
            </div>
            <button id="tv-listbtn" class="ico"></button>
        </div>
    </div>

    <div id="tv-footer-mdbar">

        <div id="tv-prog">
            <div id="tv-prog-timer">
                <span id="t1">--:--</span><span id="t2">/</span><span id="t3">--:--</span>
            </div>
            <div id="tv-prog-title">
                <?php echo $this->title ?>
            </div>
            <div id="tv-prog-seekbar" class="rr"></div>
            <div id="tv-prog-loaded" class="rr"></div>
        </div>
    </div>

    <!-- <div id="tv-footer-rtbar">

    </div> -->
</div>
<div id="tv-main-container" class="layer">
    <div id="tv-screen" class="layer text-center">
        <video id="tv-video-player" preload oncontextmenu="return false;">
            <source>
        </video>
    </div>
    <div id="tv-cover" class="layer">
        <button id="tv-fs-play-btn" class="empty-btn"></button>
        <button id="tv-fs-pause-btn" class="empty-btn"></button>
    </div>
</div>



<script type="text/javascript">
    $('document').ready(function() {
        // 网速失速
        $('#player').on('stalled', function() {
            console.log('stalled');
            var new_one = $('#player').clone(true);
            $('#player').after(new_one).remove();
        });
        // 网速错误
        $('#player').on('error', function() {
            console.log('error');
            var new_one = $('#player').clone(true);
            $('#player').after(new_one).remove();
        });
        $('#tv-listbtn').click(function() {
            $('#tv-listbar').clickToggle();
        });

        $('#tv-header').autoToggle();
        $('#tv-footer').autoToggle({
            animationDirection: 'bottom',
            beforeDisplay: function() {
                $('#tv-cover').show();
            },
            beforeHide: function() {
                if (!document.getElementById("tv-video-player").paused) {
                    $('#tv-cover').hide();
                }
            }
        });
        $('#tv-video-player').video({
            src: '<?php echo $this->video_url ?>',
            onPause: function() {
                $('#tv-fs-play-btn').show();
                $('#tv-fs-pause-btn').hide();
                $('#play').show();
                $('#pause').hide();
            },
            onEnded: function() {
                $('#tv-cover').show();
            },
            onPlay: function() {
                $('#tv-fs-play-btn').hide();
                $('#tv-fs-pause-btn').show();
                $('#play').hide();
                $('#pause').show();
            }
        });
        // play and pause
        $('#tv-fs-play-btn').click(function() {
            $('#play').click();
        });
        $('#tv-fs-pause-btn').click(function() {
            $('#pause').click();
        });
        $('#play').click(function() {
            $('#tv-video-player').video("play", function() {
                $('#tv-cover').hide();
            });
        });
        $('#pause').click(function() {
            $('#tv-video-player').video("pause", function() {
                $('#tv-cover').show();
            });
        });
        // next program
        $('#next').click(function() {

        });
        
        $('#tv-header .unvisiable').removeClass('unvisiable');
        
        
        
        
    });
    
    function getApiData() {
        $.ajax({ 
            url: "<?php echo $this->url(array(), "special-recommend")?>", 
            dataType:'json',
            success: function(result){
                console.log(result);

                $("#tv-special-name").html(result.data.name);
                $("#tv-author-name").html(result.data.author);
                $("#logo").attr('src', result.data.photo);
                $("#tv-listbar-content").html("");
                
                $.each(result.data.programs, function(i, item) {
                    $("#tv-listbar-content").append(
                        '<ul class="itm"><li class="col col1"><i class="ico play"></i></li><li class="col col2">'+ item.name +'</li><li class="col col3">'+ parseInt(item.time).timeFormat() +'</li></ul>'
                    );
                });
            }
        });
    }
</script>