
<div id="tv-footer" style="display:none">
    <div id="tv-listbar">
        <div id="tv-listbar-title">
            <a href="javascript:void(0)" id="tv-author-img"></a>
            <div class="wp">
                <div id="tvidx02">
                    <p id="tv-special-name">
                    </p>
                    <span id="tvidx01">By </span><a id="tv-author-name" href="javascript:void(0)"></a>
                </div>
                <button class="empty-btn close-btn" id="tv-listbar-close"></button>
            </div>
        </div>
        <div id="tv-listbar-content">
        </div>
    </div>
    <div id="tv-footer-ltbar">
        <div class="wp">
            <button class="ico" id="prev" class="pull-left"></button>
            <button class="ico" id="play" class="pull-left"></button>
            <button class="ico" id="pause" class="pull-left"></button>
            <button class="ico" id="next" class="pull-left"></button>
        </div>
    </div>
    <div id="tv-footer-rtbar">
        <div class="wp">
            <div id="volume-ctrl" class="pull-left">
                <button id="volume-speaker" class="ico pull-left"></button>
                <div id="volume-holder" class="pull-left">
                    <div id="volume-in"></div>
                </div>
            </div>
            <button id="tv-listbtn" class="ico"></button>
        </div>
    </div>

    <div id="tv-footer-mdbar">

        <div id="tv-prog">
            <div id="tv-prog-timer">
                <span id="t1">--:--</span><span id="t2">/</span><span id="t3">--:--</span>
            </div>
            <div id="tv-prog-title">
            </div>
            <div id="tv-prog-seekbar" class="rr"></div>
            <div id="tv-prog-loaded" class="rr"></div>
        </div>
    </div>
</div>

<div id='tv-sider'>

</div>

<div id="tv-main-container" class="layer">
    <div id="tv-screen" class="layer text-center">
        <video id="tv-video-player" preload oncontextmenu="return false;">
            <source>
        </video>
        <audio id="tv-audio-player" preload oncontextmenu="return false;">
        </audio>
    </div>
    <div id="tv-cover" class="layer">
        <button id="tv-fs-play-btn" class="empty-btn"></button>
        <button id="tv-fs-pause-btn" class="empty-btn"></button>
    </div>
    <div id="tv-audio-holder" style="position:absolute;width:600px;height:600px;background:url(/img/cd.png);left:50%;top:50%;margin-left:-300px;margin-top:-300px;">
        <div id="tv-mask" style="background-size:cover;background-position:center center;position:absolute;border-radius:1000px;width:350px;height:350px;left:50%;top:50%;margin-left:-175px;margin-top:-175px;">

        </div>
    </div>
</div>

<div class="P_tmp">
    <ul class="list-item itm">
        <li class="col col1">
            <i class="ico null"></i>
        </li>
        <li class="col col2 tv-current-title">

        </li>
        <li class="col col3">
            time here
        </li>
    </ul>
</div>

<script type="text/javascript">
    $('document').ready(function() {
        // 网速失速
        $('#player').on('stalled', function() {
            console.log('stalled');
            var new_one = $('#player').clone(true);
            $('#player').after(new_one).remove();
        });
        // 网速错误
        $('#player').on('error', function() {
            console.log('error');
            var new_one = $('#player').clone(true);
            $('#player').after(new_one).remove();
        });

        $('#tv-listbtn').click(function() {
            $('#tv-listbar').clickToggle();
        });

        var list = [
            {htmlObject: $('#tv-header')}
        ];
        $('#tv-header').mouseenter(function() {
            $.autoToggleListStop();
        });
        $('#tv-header').mouseleave(function() {
            $.autoToggleListRestart();
        });
        $.autoToggleList(list);


//        $('#tv-header').autoToggle();
//        $('#tv-footer').autoToggle({
//            animationDirection: 'bottom',
//            beforeDisplay: function() {
//                $('#tv-cover').show();
//            },
//            beforeHide: function() {
//                if (!document.getElementById("tv-video-player").paused) {
//                    $('#tv-cover').hide();
//                }
//            }
//        });
        $('#tv-screen').video({
            onPause: function() {
                $('#tv-fs-play-btn').show();
                $('#tv-fs-pause-btn').hide();
                $('#play').show();
                $('#pause').hide();
            },
            onEnded: function() {
                $('#tv-cover').show();
                nextFunc();
            },
            onPlay: function() {
                $('#tv-fs-play-btn').hide();
                $('#tv-fs-pause-btn').show();
                $('#play').hide();
                $('#pause').show();
            }
        });
        // play and pause and next and prev
        $('#tv-fs-play-btn').click(function() {
            $('#play').click();
        });
        $('#tv-fs-pause-btn').click(function() {
            $('#pause').click();
        });
        $('#play').click(function() {
            $('#tv-screen').video("play", function() {
                $('#tv-cover').hide();
            });
        });
        $('#pause').click(function() {
            $('#tv-screen').video("pause", function() {
                $('#tv-cover').show();
            });
        });
        $('#next').click(function() {
            nextFunc()
        });
        $('#prev').click(function() {
            prevFunc();
        });

        // 显示“换一批”按钮
        $('#tv-header .unvisiable').removeClass('unvisiable');

        $('#tv-header #refresh').click(function() {
            getApiData(nextFunc);
        });

        var __dura = 10000;
        $.rotateCd = function() {
            $('#tv-mask').animate({
                rotate: '+=360deg'
            }, __dura, 'linear');
        };
        $.rotateCd();
        window.setInterval("$.rotateCd()", __dura);

        getApiData(nextFunc);
    });
    function playFunc(target) {
        target.addClass('selected').find('.ico').removeClass('null').addClass('play');
        target.siblings('.list-item').removeClass('selected').find('.ico').addClass('null');
        var video_url = target.attr('video');
        var audio_url = target.attr('audio');
        var title = target.find('.tv-current-title').html();
        $('#tv-screen').video("restart", function() {
            $('#tv-cover').hide();
            $('#tv-prog-title').html(title);
        }, video_url);
    }
    function nextFunc() {
        if (playListCount()) {
            playFunc(_getSelectedItem('next'));
        } else {
            return false;
        }
    }
    function prevFunc() {
        if (playListCount()) {
            playFunc(_getSelectedItem('prev'));
        } else {
            return false;
        }
    }

    function _getSelectedItem(direction) {
        var selected = null;
        var current = $('#tv-listbar-content .list-item.selected');
        var jumpOne;
        if (direction === 'next') {
            jumpOne = $($('#tv-listbar-content .list-item').get(0));
        } else if (direction === 'prev') {
            jumpOne = $($('#tv-listbar-content .list-item').get($('#tv-listbar-content .list-item').length - 1));
        }
        if (current.length) {
            var one;
            if (direction === 'next')
                one = current.next('.list-item');
            else if (direction === 'prev')
                one = current.prev('.list-item');
            if (one.length) {
                selected = one;
            } else {
                selected = jumpOne;
            }
        } else {
            selected = jumpOne;
        }
        return selected;
    }

    function switchFunc() {

    }
    function playListCount() {
        var list_item = $('#tv-listbar-content .list-item');
        if (list_item.length) {
            return list_item.length;
        } else {
            return false;
        }
    }
    function getApiData(callback) {
<?php
$url = "";
$uid = "";

$uid = $this->uid;

if (!empty($_COOKIE["specialId"])) {
    $url = $this->url(array("uid" => $uid, "sid" => $_COOKIE["specialId"]), "api-special-recommend");
} else {
    $url = $this->url(array("uid" => $uid, "sid" => "none"), "api-special-recommend");
}
?>

        var url = "<?php echo $url ?>";
        
        $.ajax({
            url: url,
            dataType: 'json',
            success: function(result) {
                if (result.code === 200) {
                    $.cookie('specialId', result.data.id);
                    $("#tv-special-name").html(result.data.name);
                    $("#tv-author-name").html(result.data.author);
                    $("#tv-author-img").css('background-image', 'url(' + result.data.photo + ')');
                    $("#tv-listbar-content").empty();
                    $('#tv-mask').css('background-image', 'url(' + result.data.photo_main + ')');
                    $.each(result.data.programs, function() {
                        var item = $(".P_tmp .list-item").clone(true);
                        item.click(function() {
                            playFunc($(this).closest('.list-item'));
                        });
                        item.attr('video', this.oss_video);
                        item.attr('audio', this.oss_audio);
                        item.attr('id', this.id);
                        item.find('.col2').html(this.name);
                        item.find('.col3').html(parseInt(this.time).timeFormat());
                        $("#tv-listbar-content").append(item);
                    });
                    if (typeof callback === 'function') {
                        callback();
                    }
                }
            }
        });
    }
</script>
