
<script type="text/javascript" src="<?php echo $this->jsPath('player.js'); ?>"></script>


<?php
$player_mode = "video";
if ($this->me->getUser()->attribute && $this->me->getUser()->attribute['player_mode']) {
    $player_mode = $this->me->getUser()->attribute['player_mode'];
}
$bean = $this->special_bean;
?>


<div id="tv-main-container" class="layer">
    <div id='tv-sider'>
        <div class="pxt">
            <button id='btn-list' class='ico tv-side-btn'></button>
            <button id='btn-refresh' class='ico tv-side-btn'></button>
            <button id='btn-toggle' class='ico tv-side-btn'></button>
        </div>
    </div>
    <div id="tv-listbar" sid="<?php echo $bean->id ?>">
        <div class="tv-tab-content">
            <div class="tv-tab-content-head">
                <div class="alt alt-list">
                    <img class="alt-img" src="<?php echo $bean->photo ?>"/>
                    <div class="alt-title">
                        <p class="t1"><?php echo $bean->name ?></p>
                        <div class="t2">by <?php echo $bean->author ?></div>
                    </div>
                    <div class="alt-opera">
                        <button class="ico"></button>
                    </div>
                </div>
                <div class="alt alt-favor hidden">
                    <div class="alt-title">
                        <p class="t1">梁振英:勿以香港青少年前途作政治筹码</p>
                        <div class="t2">by 梁振英</div>
                    </div>
                </div>
                <div class="alt alt-hobby hidden">
                    <div class="alt-title">
                        <p class="t1">设置兴趣</p>
                        <div class="t2">根据您的兴趣推送节目</div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="tv-tab-content-body">
                <div class="alt alt-list">
                    <div class="list-item clearfix">
                        <div class="list-item-cell lt">1. 农民或获15万奖励</div>
                        <div class="list-item-cell rt sharing ico"></div>
                        <div class="list-item-cell rt duration">05:45</div>
                    </div>
                    <div class="list-item clearfix">
                        <div class="list-item-cell lt">2. 农民或获15万奖励</div>
                        <div class="list-item-cell rt sharing ico"></div>
                        <div class="list-item-cell rt duration">06:29</div>
                    </div>
                </div>
                <div class="alt alt-favor hidden">
                    <div class="list-item clearfix">
                        <div class="list-item-cell lt">1. 农民或获15万奖励</div>
                        <div class="list-item-cell rt remove-favor ico"></div>
                        <div class="list-item-cell rt sharing ico"></div>
                    </div>
                    <div class="list-item clearfix">
                        <div class="list-item-cell lt">2. 农民或获15万奖励</div>
                        <div class="list-item-cell rt remove-favor ico"></div>
                        <div class="list-item-cell rt sharing ico"></div>
                    </div>
                </div>
                <div class="alt alt-hobby hidden">
                    <div class="unit-items">
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item selected">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item selected">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item selected">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item selected">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item selected">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item selected">
                            <p>历史文化</p>
                        </div>
                        <div class="unit-item">
                            <p>历史文化</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tv-tab-list">
            <ul>
                <li>
                    <span class="selected">专辑播放列表</span>
                </li>
                <li>
                    <span>我的收藏夹</span>
                </li>
                <li>
                    <span>兴趣设置</span>
                </li>
            </ul>
            <div class="logout-btn-content">
                <button class="btn btn-gray btn-sm">安全退出</button>
            </div>
        </div>
        <button class="tv-tab-close"><i class="ico"></i></button>
    </div>

    <?php if ($player_mode == 'video'): ?>
        <div id="tv-screen" class="layer text-center">
            <video id="tv-video-player" src="http://cheesetv.oss-cn-beijing.aliyuncs.com/%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%8201%E9%A3%9F%E5%93%81%E4%BF%9D%E8%B4%A8%E6%9C%9F%E6%98%AF%E4%B8%8D%E6%98%AF%E6%9C%80%E5%90%8E%E5%8F%AF%E9%A3%9F%E7%94%A8%E6%9C%9F%E9%99%90.mp4" preload oncontextmenu="return false;">
            </video>
        </div>
    <?php else: ?>
        <div id="tv-disk">
            <div id="tv-disk-page"></div>
        </div>
    <?php endif; ?>

    <div id="tv-ctrl-block">
        <div id="tv-ctrl-c">
            <div id="tv-ctrl-prog">

            </div>
        </div>
        <div id="tv-ctrl-play" class="tv-ctrl-s">
            <i class="ico"></i>
        </div>
        <div id="tv-ctrl-fullscreen" full='no' class="tv-ctrl-s">
            <i class="ico"></i>
        </div>
    </div>

</div>

<div class="P_tmp">
    <ul class="list-item itm">
        <li class="col col1">
            <i class="ico null"></i>
        </li>
        <li class="col col2 tv-current-title">

        </li>
        <li class="col col3">
            time here
        </li>
    </ul>
</div>



<!--<button id="seeking-testing-btn" style="position:fixed;z-index:100;bottom:100px;left:100px;padding:10px;">SEEKING BTN</button>-->

<input type="hidden" id="uid" value="<?php echo $this->uid ?>"/>

<script type="text/javascript">
    var init_player_mode = '<?php echo $player_mode; ?>';

    $('document').ready(function() {
    });
    $('.tv-toggle-unit[rel="' + init_player_mode + '"]').addClass('selected');
    if (init_player_mode === 'audio') {

    } else {

    }

    // 网速失速
    $('#player').on('stalled', function() {
        console.log('stalled');
        var new_one = $('#player').clone(true);
        $('#player').after(new_one).remove();
    });
    // 网速错误
    $('#player').on('error', function() {
        console.log('error');
        var new_one = $('#player').clone(true);
        $('#player').after(new_one).remove();
    });
    var list = [
        {htmlObject: $('#tv-sider')},
        {htmlObject: $('#tv-ctrl-block')}
    ];
    $('#tv-sider, #tv-ctrl-block, #tv-listbar').mouseenter(function() {
        $.autoToggleListStop();
    });
    $('#tv-sider, #tv-ctrl-block, #tv-listbar').mouseleave(function() {
        $.autoToggleListRestart();
    });
    $.autoToggleList(list);

</script>

